/**
 * Platform-owned Node server entry for deployed TanStack Start projects.
 *
 * Why this exists
 * ───────────────
 * TanStack Start projects are imported as `framework_id="vite-react"` (the
 * proven Vite dev runtime is kept for preview — see
 * projects/detect-tanstack-start.ts). Their `vite build` (the Lovable export
 * pins `@lovable.dev/vite-tanstack-config`, whose nitro preset is
 * `cloudflare-module`) emits:
 *
 *   dist/client/         static client assets
 *   dist/server/server.js  a WinterCG web-fetch handler  `{ fetch(req, env, ctx) }`
 *
 * That is NOT a listening server, so it cannot be served by the static-files
 * deploy path (no root index.html → 404). This entry adapts it to a
 * long-lived Node server so the existing `node-standalone` runtime adapter
 * (systemd unit + Caddy reverse_proxy) can host it exactly like Next.js/Nuxt:
 *
 *   - serves dist/client/* as static assets
 *   - bridges every other request to the web-fetch handler for SSR
 *   - listens on PORT / HOST allocated by the runtime adapter
 *
 * The string is written verbatim to `dist-server/index.mjs` by the
 * doable-cloud deploy adapter at publish time (a build artifact — it never
 * touches the imported project's own source). Uses only Node built-ins, so
 * the staged `dist-server/` needs no extra dependencies beyond the
 * self-contained build output.
 *
 * Kept as a single string (not a .mjs asset on disk) so it survives the
 * tsx-from-source runtime and the docker image's dist-less layout, mirroring
 * how nextjs-app.ts embeds DEFAULT_NEXT_CONFIG.
 */
export const TANSTACK_NODE_SERVER_ENTRY = `// AUTO-GENERATED by Doable deploy — do not edit.
// Runs a TanStack Start (cloudflare-module) build as a long-lived Node server.
import { createServer } from "node:http";
import { Readable } from "node:stream";
import { stat, readFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";
import handlerMod from "./dist/server/server.js";

const handler = handlerMod && handlerMod.fetch ? handlerMod : (handlerMod && handlerMod.default);
if (!handler || typeof handler.fetch !== "function") {
  console.error("[doable-tanstack-server] dist/server/server.js has no { fetch } export");
  process.exit(1);
}

const CLIENT = fileURLToPath(new URL("./dist/client/", import.meta.url));
const PORT = Number(process.env.PORT || 3000);
const HOST = process.env.HOST || "0.0.0.0";
// Per-app data token for @doable/ai|data (they read globalThis.__DOABLE_DATA_TOKEN).
// From env or the .doable-data-token file staged next to this entry by
// doable-cloud. Injected into SSR HTML below — the SSR analogue of the static
// injectDataToken() (which needs an index.html the SSR path doesn't produce).
const DATA_TOKEN = (() => {
  if (process.env.__DOABLE_DATA_TOKEN) return process.env.__DOABLE_DATA_TOKEN;
  try {
    return readFileSync(fileURLToPath(new URL("./.doable-data-token", import.meta.url)), "utf8").trim();
  } catch { return ""; }
})();
const TOKEN_SNIPPET = DATA_TOKEN
  ? "<script>window.__DOABLE_DATA_TOKEN=" + JSON.stringify(DATA_TOKEN) + ";</script>"
  : "";

// Doable API origin — where /__doable/ai/chat lives. Defaults to the co-located
// API on 127.0.0.1:4000; can be overridden with DOABLE_API_ORIGIN env for
// cross-host installs.
const DOABLE_API_ORIGIN = process.env.DOABLE_API_ORIGIN || "http://127.0.0.1:4000";

// ── Lovable /api/chat → Doable /__doable/ai/chat bridge ──────────────────────
// Lovable-exported TanStack Start apps ship a self-hosted AI chat pattern:
//   client: useChat({ transport: DefaultChatTransport({ api: "/api/chat" }) })
//   server: src/routes/api/chat.ts reads process.env.LOVABLE_API_KEY and calls
//           createLovableAiGatewayProvider — which does not exist on Doable.
// On Doable, AI credits + provider routing live at POST /__doable/ai/chat and
// require Authorization: Bearer <window.__DOABLE_DATA_TOKEN>. Rather than force
// every imported project to be rewritten, intercept POST /api/chat here BEFORE
// the SSR handler ever sees it, translate the AI-SDK UIMessage[] body into the
// Doable ChatMessage[] format, forward with the staged data token, and emit the
// response in the AI-SDK v5 UI Message Stream shape @ai-sdk/react's useChat
// expects. Non-streaming under the hood (Doable's stream:false JSON response),
// re-emitted as a single-shot text-delta event so useChat/toUIMessageStream
// rendering works unchanged. Applies to EVERY Lovable AI-chat import — no
// per-project source edits, no rebuild. See BUG-2026-07-15-lovable-ai-chat.
async function readRequestBody(req) {
  const chunks = [];
  for await (const c of req) chunks.push(c);
  return Buffer.concat(chunks).toString("utf8");
}

function extractText(m) {
  if (typeof m?.content === "string") return m.content;
  if (Array.isArray(m?.parts)) {
    return m.parts.filter((p) => p && p.type === "text").map((p) => p.text || "").join("");
  }
  return "";
}

async function proxyLovableChat(req, res) {
  const raw = await readRequestBody(req);
  let body = {};
  try { body = JSON.parse(raw || "{}"); } catch { body = {}; }
  const uiMessages = Array.isArray(body.messages) ? body.messages : [];
  const messages = uiMessages
    .map((m) => ({ role: (m && m.role) || "user", content: extractText(m) }))
    .filter((m) => typeof m.content === "string" && m.content.length > 0);
  if (messages.length === 0) {
    res.writeHead(400, { "content-type": "text/plain" });
    res.end("Empty messages");
    return;
  }
  if (!DATA_TOKEN) {
    res.writeHead(500, { "content-type": "text/plain" });
    res.end("Doable data token unavailable — is .doable-data-token staged?");
    return;
  }

  let upstream;
  try {
    upstream = await fetch(DOABLE_API_ORIGIN + "/__doable/ai/chat", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: "Bearer " + DATA_TOKEN,
        origin: "http://" + (req.headers.host || HOST),
      },
      body: JSON.stringify({ messages, stream: false }),
    });
  } catch (err) {
    res.writeHead(502, { "content-type": "text/plain" });
    res.end("Doable AI unreachable: " + (err && err.message || err));
    return;
  }
  if (!upstream.ok) {
    const errText = await upstream.text().catch(() => "");
    res.writeHead(upstream.status, { "content-type": "text/plain" });
    res.end("Doable AI error " + upstream.status + ": " + errText.slice(0, 500));
    return;
  }
  let payload;
  try { payload = await upstream.json(); }
  catch { payload = { content: "" }; }
  const content = (payload && typeof payload.content === "string") ? payload.content : "";

  // AI SDK v5 UI Message Stream (single-shot). @ai-sdk/react useChat consumes
  // these events via DefaultChatTransport and renders the assistant message.
  const msgId = "m_" + Date.now().toString(36);
  const events = [
    { type: "start" },
    { type: "start-step" },
    { type: "text-start", id: msgId },
    { type: "text-delta", id: msgId, delta: content },
    { type: "text-end", id: msgId },
    { type: "finish-step" },
    { type: "finish" },
  ];
  res.writeHead(200, {
    "content-type": "text/event-stream",
    "cache-control": "no-cache, no-transform",
    connection: "keep-alive",
    "x-vercel-ai-ui-message-stream": "v1",
  });
  for (const ev of events) res.write("data: " + JSON.stringify(ev) + "\\n\\n");
  res.write("data: [DONE]\\n\\n");
  res.end();
}
const MIME = {
  ".js": "text/javascript", ".mjs": "text/javascript", ".css": "text/css",
  ".html": "text/html", ".json": "application/json", ".svg": "image/svg+xml",
  ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
  ".gif": "image/gif", ".webp": "image/webp", ".avif": "image/avif",
  ".ico": "image/x-icon", ".woff": "font/woff", ".woff2": "font/woff2",
  ".ttf": "font/ttf", ".eot": "application/vnd.ms-fontobject",
  ".map": "application/json", ".txt": "text/plain", ".wasm": "application/wasm",
};

createServer(async (req, res) => {
  try {
    const pathname = decodeURIComponent(new URL(req.url, "http://localhost").pathname);

    // Lovable AI-chat bridge: intercept POST /api/chat BEFORE the SSR handler
    // so Lovable-exported chatbots (which self-host /api/chat + LOVABLE_API_KEY)
    // work on Doable without any source edit. Forwards to /__doable/ai/chat
    // with the staged Bearer token and re-emits the response as an AI-SDK v5
    // UI Message Stream so @ai-sdk/react's useChat renders it unchanged.
    if (pathname === "/api/chat" && req.method === "POST") {
      await proxyLovableChat(req, res);
      return;
    }

    // Static client asset? ("/" is always SSR; never serve directory paths.)
    if (pathname !== "/" && !pathname.endsWith("/") && !pathname.includes("..")) {
      const fp = join(CLIENT, pathname.replace(/^\\/+/, ""));
      if (fp.startsWith(CLIENT)) {
        try {
          const s = await stat(fp);
          if (s.isFile()) {
            const ext = fp.slice(fp.lastIndexOf("."));
            res.writeHead(200, {
              "content-type": MIME[ext] || "application/octet-stream",
              "cache-control": ext === ".html" ? "no-cache" : "public, max-age=31536000, immutable",
            });
            res.end(await readFile(fp));
            return;
          }
        } catch { /* not a static file — fall through to SSR */ }
      }
    }
    // SSR via the web-fetch handler.
    const url = "http://" + (req.headers.host || HOST) + req.url;
    const headers = new Headers();
    for (const [k, v] of Object.entries(req.headers)) {
      if (v !== undefined) headers.set(k, Array.isArray(v) ? v.join(", ") : v);
    }
    const init = { method: req.method, headers };
    if (req.method !== "GET" && req.method !== "HEAD") {
      init.body = Readable.toWeb(req);
      init.duplex = "half";
    }
    const response = await handler.fetch(new Request(url, init), {}, {
      waitUntil() {}, passThroughOnException() {},
    });
    const out = {};
    response.headers.forEach((v, k) => { out[k] = v; });
    const ct = response.headers.get("content-type") || "";
    // Inject the per-app data token into SSR HTML so @doable/ai|data authenticate
    // from the published origin (they read globalThis.__DOABLE_DATA_TOKEN, which
    // preview sets via a bridge and static publishes bake into index.html).
    if (TOKEN_SNIPPET && ct.includes("text/html")) {
      let html = await response.text();
      if (!html.includes("__DOABLE_DATA_TOKEN")) {
        html = /<head[^>]*>/i.test(html)
          ? html.replace(/(<head[^>]*>)/i, "$1" + TOKEN_SNIPPET)
          : TOKEN_SNIPPET + html;
      }
      const buf = Buffer.from(html, "utf8");
      delete out["content-length"];
      delete out["content-encoding"];
      out["content-length"] = String(buf.length);
      res.writeHead(response.status, out);
      res.end(buf);
      return;
    }
    res.writeHead(response.status, out);
    if (response.body) Readable.fromWeb(response.body).pipe(res);
    else res.end();
  } catch (err) {
    if (!res.headersSent) res.writeHead(500, { "content-type": "text/plain" });
    res.end("Internal Server Error");
    console.error("[doable-tanstack-server]", err);
  }
}).listen(PORT, HOST, () => {
  console.log("[doable-tanstack-server] listening on " + HOST + ":" + PORT);
});
`;
