/**
 * Platform-owned Node server entry for deployed TanStack Start projects.
 *
 * Why this exists
 * ───────────────
 * TanStack Start projects are imported as `framework_id="vite-react"` (the
 * proven Vite dev runtime is kept for preview — see
 * projects/detect-tanstack-start.ts). Their `vite build` (the Lovable export
 * pins `@lovable.dev/vite-tanstack-config`, whose nitro preset is
 * `cloudflare-module`) emits:
 *
 *   dist/client/         static client assets
 *   dist/server/server.js  a WinterCG web-fetch handler  `{ fetch(req, env, ctx) }`
 *
 * That is NOT a listening server, so it cannot be served by the static-files
 * deploy path (no root index.html → 404). This entry adapts it to a
 * long-lived Node server so the existing `node-standalone` runtime adapter
 * (systemd unit + Caddy reverse_proxy) can host it exactly like Next.js/Nuxt:
 *
 *   - serves dist/client/* as static assets
 *   - bridges every other request to the web-fetch handler for SSR
 *   - listens on PORT / HOST allocated by the runtime adapter
 *
 * The string is written verbatim to `dist-server/index.mjs` by the
 * doable-cloud deploy adapter at publish time (a build artifact — it never
 * touches the imported project's own source). Uses only Node built-ins, so
 * the staged `dist-server/` needs no extra dependencies beyond the
 * self-contained build output.
 *
 * Kept as a single string (not a .mjs asset on disk) so it survives the
 * tsx-from-source runtime and the docker image's dist-less layout, mirroring
 * how nextjs-app.ts embeds DEFAULT_NEXT_CONFIG.
 */
export const TANSTACK_NODE_SERVER_ENTRY = `// AUTO-GENERATED by Doable deploy — do not edit.
// Runs a TanStack Start (cloudflare-module) build as a long-lived Node server.
import { createServer } from "node:http";
import { Readable } from "node:stream";
import { stat, readFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";
import handlerMod from "./dist/server/server.js";

const handler = handlerMod && handlerMod.fetch ? handlerMod : (handlerMod && handlerMod.default);
if (!handler || typeof handler.fetch !== "function") {
  console.error("[doable-tanstack-server] dist/server/server.js has no { fetch } export");
  process.exit(1);
}

const CLIENT = fileURLToPath(new URL("./dist/client/", import.meta.url));
const PORT = Number(process.env.PORT || 3000);
const HOST = process.env.HOST || "0.0.0.0";
// Per-app data token for @doable/ai|data (they read globalThis.__DOABLE_DATA_TOKEN).
// From env or the .doable-data-token file staged next to this entry by
// doable-cloud. Injected into SSR HTML below — the SSR analogue of the static
// injectDataToken() (which needs an index.html the SSR path doesn't produce).
const DATA_TOKEN = (() => {
  if (process.env.__DOABLE_DATA_TOKEN) return process.env.__DOABLE_DATA_TOKEN;
  try {
    return readFileSync(fileURLToPath(new URL("./.doable-data-token", import.meta.url)), "utf8").trim();
  } catch { return ""; }
})();
const TOKEN_SNIPPET = DATA_TOKEN
  ? "<script>window.__DOABLE_DATA_TOKEN=" + JSON.stringify(DATA_TOKEN) + ";</script>"
  : "";
const MIME = {
  ".js": "text/javascript", ".mjs": "text/javascript", ".css": "text/css",
  ".html": "text/html", ".json": "application/json", ".svg": "image/svg+xml",
  ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
  ".gif": "image/gif", ".webp": "image/webp", ".avif": "image/avif",
  ".ico": "image/x-icon", ".woff": "font/woff", ".woff2": "font/woff2",
  ".ttf": "font/ttf", ".eot": "application/vnd.ms-fontobject",
  ".map": "application/json", ".txt": "text/plain", ".wasm": "application/wasm",
};

createServer(async (req, res) => {
  try {
    const pathname = decodeURIComponent(new URL(req.url, "http://localhost").pathname);
    // Static client asset? ("/" is always SSR; never serve directory paths.)
    if (pathname !== "/" && !pathname.endsWith("/") && !pathname.includes("..")) {
      const fp = join(CLIENT, pathname.replace(/^\\/+/, ""));
      if (fp.startsWith(CLIENT)) {
        try {
          const s = await stat(fp);
          if (s.isFile()) {
            const ext = fp.slice(fp.lastIndexOf("."));
            res.writeHead(200, {
              "content-type": MIME[ext] || "application/octet-stream",
              "cache-control": ext === ".html" ? "no-cache" : "public, max-age=31536000, immutable",
            });
            res.end(await readFile(fp));
            return;
          }
        } catch { /* not a static file — fall through to SSR */ }
      }
    }
    // SSR via the web-fetch handler.
    const url = "http://" + (req.headers.host || HOST) + req.url;
    const headers = new Headers();
    for (const [k, v] of Object.entries(req.headers)) {
      if (v !== undefined) headers.set(k, Array.isArray(v) ? v.join(", ") : v);
    }
    const init = { method: req.method, headers };
    if (req.method !== "GET" && req.method !== "HEAD") {
      init.body = Readable.toWeb(req);
      init.duplex = "half";
    }
    const response = await handler.fetch(new Request(url, init), {}, {
      waitUntil() {}, passThroughOnException() {},
    });
    const out = {};
    response.headers.forEach((v, k) => { out[k] = v; });
    const ct = response.headers.get("content-type") || "";
    // Inject the per-app data token into SSR HTML so @doable/ai|data authenticate
    // from the published origin (they read globalThis.__DOABLE_DATA_TOKEN, which
    // preview sets via a bridge and static publishes bake into index.html).
    if (TOKEN_SNIPPET && ct.includes("text/html")) {
      let html = await response.text();
      if (!html.includes("__DOABLE_DATA_TOKEN")) {
        html = /<head[^>]*>/i.test(html)
          ? html.replace(/(<head[^>]*>)/i, "$1" + TOKEN_SNIPPET)
          : TOKEN_SNIPPET + html;
      }
      const buf = Buffer.from(html, "utf8");
      delete out["content-length"];
      delete out["content-encoding"];
      out["content-length"] = String(buf.length);
      res.writeHead(response.status, out);
      res.end(buf);
      return;
    }
    res.writeHead(response.status, out);
    if (response.body) Readable.fromWeb(response.body).pipe(res);
    else res.end();
  } catch (err) {
    if (!res.headersSent) res.writeHead(500, { "content-type": "text/plain" });
    res.end("Internal Server Error");
    console.error("[doable-tanstack-server]", err);
  }
}).listen(PORT, HOST, () => {
  console.log("[doable-tanstack-server] listening on " + HOST + ":" + PORT);
});
`;
