import type { ProviderPreset } from "./provider-types";
import { CLOUD_CAPS_FULL, CLOUD_CAPS_NO_VISION } from "./provider-data-cloud-major";

export const CLOUD_SPECIAL_PROVIDERS = [
  // Tier 3 — Specialized Cloud (9)
  // ═══════════════════════════════════════════════════════════
  {
    id: "groq",
    name: "Groq",
    category: "cloud",
    subcategory: "specialized",
    sdkType: "openai",
    defaultBaseUrl: "https://api.groq.com/openai/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPrefix: "gsk_",
    apiKeyPlaceholder: "gsk_...",
    apiKeyHelpUrl: "https://console.groq.com/keys",
    supportsModelDiscovery: true,
    defaultModels: [
      { id: "llama-3.3-70b-versatile", name: "Llama 3.3 70B", contextWindow: 128_000, supportsTools: true, supportsVision: false, tier: "balanced" },
      { id: "mixtral-8x7b-32768", name: "Mixtral 8x7B", contextWindow: 32_000, supportsTools: true, supportsVision: false, tier: "fast" },
    ],
    icon: "groq",
    description: "Ultra-fast LPU inference — free tier with no credit card",
    capabilities: CLOUD_CAPS_FULL,
    freeTier: "All models free, no CC, 30 RPM",
    tags: ["free", "fast", "popular"],
  },
  {
    id: "mistral",
    name: "Mistral AI",
    category: "cloud",
    subcategory: "specialized",
    sdkType: "openai",
    defaultBaseUrl: "https://api.mistral.ai/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "Mistral API key",
    apiKeyHelpUrl: "https://console.mistral.ai/api-keys",
    supportsModelDiscovery: true,
    defaultModels: [
      { id: "mistral-large-latest", name: "Mistral Large", contextWindow: 128_000, supportsTools: true, supportsVision: true, tier: "powerful" },
      { id: "mistral-small-latest", name: "Mistral Small", contextWindow: 32_000, supportsTools: true, supportsVision: false, tier: "fast" },
    ],
    icon: "mistral",
    description: "European AI lab with strong open-weight models",
    capabilities: CLOUD_CAPS_FULL,
    freeTier: "Experiment plan free",
    tags: ["free", "european", "open-source"],
  },
  {
    id: "cohere",
    name: "Cohere",
    category: "cloud",
    subcategory: "specialized",
    sdkType: "openai",
    defaultBaseUrl: "https://api.cohere.ai/compatibility/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "Cohere API key",
    apiKeyHelpUrl: "https://dashboard.cohere.com/api-keys",
    supportsModelDiscovery: true,
    defaultModels: [
      { id: "command-r-plus", name: "Command R+", contextWindow: 128_000, supportsTools: true, supportsVision: false, tier: "powerful" },
    ],
    icon: "cohere",
    description: "Enterprise-focused RAG and command models",
    capabilities: CLOUD_CAPS_FULL,
    freeTier: "1K calls/month",
    tags: ["free", "enterprise", "rag"],
  },
  {
    id: "xai",
    name: "xAI (Grok)",
    category: "cloud",
    subcategory: "specialized",
    sdkType: "openai",
    defaultBaseUrl: "https://api.x.ai/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPrefix: "xai-",
    apiKeyPlaceholder: "xai-...",
    apiKeyHelpUrl: "https://console.x.ai/",
    supportsModelDiscovery: true,
    defaultModels: [
      { id: "grok-4", name: "Grok 4", contextWindow: 128_000, supportsTools: true, supportsVision: true, tier: "powerful" },
      { id: "grok-3-mini", name: "Grok 3 Mini", contextWindow: 128_000, supportsTools: true, supportsVision: true, tier: "fast" },
    ],
    icon: "xai",
    description: "Grok models from xAI with generous free tier",
    capabilities: CLOUD_CAPS_FULL,
    freeTier: "$25 free + $150/mo",
    tags: ["free", "grok"],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    category: "cloud",
    subcategory: "specialized",
    sdkType: "openai",
    defaultBaseUrl: "https://api.deepseek.com",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPrefix: "dsk-",
    apiKeyPlaceholder: "dsk-...",
    apiKeyHelpUrl: "https://platform.deepseek.com/api_keys",
    supportsModelDiscovery: true,
    defaultModels: [
      { id: "deepseek-chat", name: "DeepSeek Chat", contextWindow: 128_000, supportsTools: true, supportsVision: false, tier: "balanced" },
      { id: "deepseek-reasoner", name: "DeepSeek Reasoner", contextWindow: 64_000, supportsTools: true, supportsVision: false, tier: "powerful" },
    ],
    icon: "deepseek",
    description: "Cost-effective reasoning and chat models from China",
    capabilities: CLOUD_CAPS_NO_VISION,
    freeTier: "Free tokens",
    tags: ["free", "reasoning", "cheap"],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    category: "cloud",
    subcategory: "specialized",
    sdkType: "openai",
    defaultBaseUrl: "https://api.perplexity.ai",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPrefix: "pplx-",
    apiKeyPlaceholder: "pplx-...",
    apiKeyHelpUrl: "https://www.perplexity.ai/settings/api",
    supportsModelDiscovery: false,
    defaultModels: [],
    icon: "perplexity",
    description: "Search-augmented AI with real-time web access",
    capabilities: CLOUD_CAPS_NO_VISION,
    tags: ["search", "web"],
  },
  {
    id: "sambanova",
    name: "SambaNova",
    category: "cloud",
    subcategory: "specialized",
    sdkType: "openai",
    defaultBaseUrl: "https://api.sambanova.ai/v1",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "SambaNova API key",
    apiKeyHelpUrl: "https://cloud.sambanova.ai/",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "sambanova",
    description: "High-throughput AI inference on custom hardware",
    capabilities: CLOUD_CAPS_FULL,
    freeTier: "$5 free credits",
    tags: ["free", "fast"],
  },
  {
    id: "novita-ai",
    name: "Novita AI",
    category: "cloud",
    subcategory: "specialized",
    sdkType: "openai",
    defaultBaseUrl: "https://api.novita.ai/v3/openai",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "Novita AI API key",
    apiKeyHelpUrl: "https://novita.ai/dashboard/key",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "novita",
    description: "Affordable GPU cloud for LLM and image generation",
    capabilities: CLOUD_CAPS_FULL,
    freeTier: "Yes",
    tags: ["free", "cheap"],
  },
  {
    id: "ppio",
    name: "PPIO",
    category: "cloud",
    subcategory: "specialized",
    sdkType: "openai",
    defaultBaseUrl: "https://api.ppinfra.com/v3/openai",
    baseUrlEditable: false,
    authMethod: "bearer",
    apiKeyPlaceholder: "PPIO API key",
    apiKeyHelpUrl: "https://ppinfra.com/",
    supportsModelDiscovery: true,
    defaultModels: [],
    icon: "ppio",
    description: "Decentralized AI inference infrastructure",
    capabilities: CLOUD_CAPS_FULL,
    tags: ["infrastructure"],
  },

  // ═══════════════════════════════════════════════════════════
] as const satisfies readonly ProviderPreset[];