/**
 * Vite Plugin: Source Annotations
 *
 * Injects `data-source="filepath:line:col"` attributes into JSX elements
 * at compile time. This allows the visual editor to map DOM elements back
 * to their source code location for click-to-edit functionality.
 *
 * The plugin code is generated as a JS string and written into each
 * project's `.doable/` directory, then referenced from vite.config.ts.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { existsSync } from "node:fs";

// ─── Plugin Code Generator ──────────────────────────────

/**
 * Returns the JavaScript source for the Vite plugin that will be
 * written to each project's `.doable/vite-plugin-source-annotations.js`.
 */
export function generateSourceAnnotationsPlugin(): string {
  return `// Auto-generated by Doable — do not edit manually.
// This Vite plugin injects data-source attributes into JSX-style markup
// elements so the visual editor can map DOM elements back to source code.
//
// Supported file extensions:
//   .jsx / .tsx  — full file is JSX.
//   .vue         — markup inside the first <template>...</template> block.
//   .svelte      — markup outside <script> and <style> blocks.
//   .astro       — markup after the second \`---\` frontmatter terminator.
//
// Fragility note: markup extraction for .vue / .svelte / .astro is
// regex-based and best-effort. It does NOT use a real parser, so it can
// be confused by unusual constructs (e.g. nested template strings that
// look like tags, multiple <template> blocks in a Vue SFC, comments that
// straddle block boundaries). Line numbers in the original file are
// preserved so click-to-edit stays accurate even when extraction is
// imperfect.

/**
 * @returns {import('vite').Plugin}
 */
export default function doableSourceAnnotations() {
  let projectRoot = "";

  return {
    name: "doable-source-annotations",
    enforce: "pre",

    configResolved(config) {
      projectRoot = config.root;
    },

    transform(code, id) {
      // Only run in development mode
      if (this.environment?.mode !== "development" && process.env.NODE_ENV === "production") {
        return null;
      }

      // Skip node_modules and .doable directory
      if (id.includes("node_modules") || id.includes(".doable")) {
        return null;
      }

      // Strip query string (e.g. .vue?vue&type=template) before extension match
      const cleanId = id.split("?")[0];

      // Only process supported markup-bearing files
      if (!/\\.(?:[jt]sx|vue|svelte|astro)$/.test(cleanId)) {
        return null;
      }

      // Compute file path relative to project root
      let relPath = id;
      if (projectRoot && id.startsWith(projectRoot)) {
        relPath = id.slice(projectRoot.length);
        // Remove leading slash/backslash
        relPath = relPath.replace(/^[\\\\/]/, "");
      }
      // Normalize to forward slashes
      relPath = relPath.replace(/\\\\/g, "/");

      // Dispatch by extension
      if (/\\.[jt]sx$/.test(cleanId)) return transformJsx(code, relPath);
      if (/\\.vue$/.test(cleanId)) {
        return transformBlockMarkup(code, relPath, /<template[^>]*>([\\s\\S]*?)<\\/template>/);
      }
      if (/\\.svelte$/.test(cleanId)) return transformSvelteMarkup(code, relPath);
      if (/\\.astro$/.test(cleanId)) return transformAstroMarkup(code, relPath);
      return null;
    },
  };
}

/**
 * Regex-based JSX transform that adds data-source attributes.
 *
 * Strategy:
 * 1. Split code into lines to track line numbers.
 * 2. Walk through each character, tracking whether we are inside
 *    a string literal, template literal, or comment.
 * 3. When we find a JSX opening tag (< followed by a valid tag name),
 *    insert data-source after the tag name.
 *
 * This is intentionally simple — it doesn't need to be perfect,
 * just good enough for dev-time source mapping.
 */
function transformJsx(code, filePath) {
  const lines = code.split("\\n");
  const result = [];
  let lineNum = 0;

  for (const line of lines) {
    lineNum++;
    result.push(processLine(line, filePath, lineNum));
  }

  return {
    code: result.join("\\n"),
    map: null, // sourcemap not needed for dev annotations
  };
}

/**
 * Process a single line, injecting data-source attributes into JSX tags.
 * Skips tags that appear inside string literals or comments.
 */
function processLine(line, filePath, lineNum) {
  // Skip lines that are purely comments
  const trimmed = line.trim();
  if (trimmed.startsWith("//") || trimmed.startsWith("*") || trimmed.startsWith("/*")) {
    return line;
  }

  // Match JSX opening tags:
  //   <Component   <div   <MyComponent.Sub   <ns:tag
  // But NOT:
  //   </closing>   <=comparison   <<bitshift   <T>(generic)
  //
  // The regex captures:
  //   Group 1: the full tag name (e.g., "div", "Component", "My.Sub")
  //   The match starts with < and a letter (uppercase or lowercase)
  //
  // We insert data-source after the tag name.
  const tagRegex = /<([A-Z][a-zA-Z0-9.]*|[a-z][a-zA-Z0-9-]*)(?=[\\s/>]|$)/g;

  let output = "";
  let lastIndex = 0;
  let match;

  while ((match = tagRegex.exec(line)) !== null) {
    const matchStart = match.index;
    const tagName = match[1];
    const afterTagName = matchStart + match[0].length;

    // Column is 1-based
    const col = matchStart + 1;

    // Skip if this looks like it's inside a string
    if (isInsideString(line, matchStart)) {
      continue;
    }

    // Skip closing tags — check if there's a / before the tag name
    if (matchStart > 0 && line[matchStart + 1] === "/") {
      continue;
    }

    // Skip TypeScript generic type parameters:
    // If the character before < is a word character (letter/digit/_),
    // it's a generic like Array<T>, ChangeEvent<HTMLInputElement>, etc.
    // JSX tags always follow non-word chars: whitespace, (, {, =, etc.
    if (matchStart > 0) {
      const prevChar = line[matchStart - 1];
      if (/[a-zA-Z0-9_]/.test(prevChar)) {
        continue;
      }
    }

    // Skip certain tags that shouldn't get annotations
    // (fragments, generic type params, etc.)
    if (tagName === "T" || tagName === "K" || tagName === "V" || tagName === "P") {
      // Likely a generic type parameter — skip single uppercase letters
      // unless followed by a space and attributes (heuristic)
      const after = line[afterTagName];
      if (after === ">" || after === ",") {
        continue;
      }
    }

    const sourceAttr = \` data-source="\${filePath}:\${lineNum}:\${col}"\`;

    // Append everything up to after the tag name, then the attribute
    output += line.slice(lastIndex, afterTagName);
    output += sourceAttr;
    lastIndex = afterTagName;
  }

  // Append the rest of the line
  output += line.slice(lastIndex);

  return output;
}

/**
 * Simple heuristic to detect if a position is inside a string literal.
 * Counts unescaped quotes before the position.
 */
function isInsideString(line, pos) {
  let inSingle = false;
  let inDouble = false;
  let inTemplate = false;

  for (let i = 0; i < pos; i++) {
    const ch = line[i];
    const prev = i > 0 ? line[i - 1] : "";

    if (prev === "\\\\") continue; // escaped character

    if (ch === "'" && !inDouble && !inTemplate) {
      inSingle = !inSingle;
    } else if (ch === '"' && !inSingle && !inTemplate) {
      inDouble = !inDouble;
    } else if (ch === "\\\`" && !inSingle && !inDouble) {
      inTemplate = !inTemplate;
    }
  }

  return inSingle || inDouble || inTemplate;
}

/**
 * Extract the inner content of the first markup block matched by
 * \`blockRegex\` (capture group 1 is the inner markup), run the JSX
 * tag-injection logic on it, and splice the result back into the
 * original code at the same byte offset.
 *
 * Line numbers are preserved because we only rewrite within the matched
 * span and do not add or remove newlines.
 */
function transformBlockMarkup(code, filePath, blockRegex) {
  const m = blockRegex.exec(code);
  if (!m) return null;
  const fullMatch = m[0];
  const inner = m[1];
  // Locate the inner content inside the matched block. The opening tag
  // ends at the first \`>\` of the match; everything after that and
  // before the closing tag is captured.
  const openTagEnd = fullMatch.indexOf(">") + 1;
  const innerStart = m.index + openTagEnd;
  // Sanity check: the slice should equal the captured inner content.
  if (code.slice(innerStart, innerStart + inner.length) !== inner) {
    return null;
  }
  const startLine = code.slice(0, innerStart).split("\\n").length;
  const lines = inner.split("\\n");
  const processed = lines
    .map((line, idx) => processLine(line, filePath, startLine + idx))
    .join("\\n");
  const newCode =
    code.slice(0, innerStart) + processed + code.slice(innerStart + inner.length);
  return { code: newCode, map: null };
}

/**
 * Svelte: markup is everything that is NOT inside a top-level
 * <script> or <style> block. We mark the line ranges covered by those
 * blocks and skip them, annotating the rest in place so original line
 * numbers are preserved.
 */
function transformSvelteMarkup(code, filePath) {
  const blocked = new Set();
  const markBlocks = (regex) => {
    let m;
    while ((m = regex.exec(code)) !== null) {
      const startLine = code.slice(0, m.index).split("\\n").length;
      const endLine = code.slice(0, m.index + m[0].length).split("\\n").length;
      for (let i = startLine; i <= endLine; i++) blocked.add(i);
    }
  };
  markBlocks(/<script[^>]*>[\\s\\S]*?<\\/script>/gi);
  markBlocks(/<style[^>]*>[\\s\\S]*?<\\/style>/gi);

  const lines = code.split("\\n");
  const result = lines.map((line, idx) => {
    const lineNum = idx + 1;
    if (blocked.has(lineNum)) return line;
    return processLine(line, filePath, lineNum);
  });
  return { code: result.join("\\n"), map: null };
}

/**
 * Astro: optional frontmatter is delimited by a leading \`---\` line and
 * a closing \`---\` line. Everything after the closing \`---\` is markup.
 * If no frontmatter is present, the whole file is treated as markup.
 */
function transformAstroMarkup(code, filePath) {
  const lines = code.split("\\n");
  let bodyStart = 0;
  if (lines[0] !== undefined && lines[0].trim() === "---") {
    for (let i = 1; i < lines.length; i++) {
      if (lines[i].trim() === "---") {
        bodyStart = i + 1;
        break;
      }
    }
  }
  const result = lines.map((line, idx) => {
    if (idx < bodyStart) return line;
    return processLine(line, filePath, idx + 1);
  });
  return { code: result.join("\\n"), map: null };
}
`;
}

// ─── Plugin Installation ─────────────────────────────────

/**
 * Ensure the source annotations plugin is installed in a project.
 *
 * 1. Writes the plugin JS file to `{projectPath}/.doable/vite-plugin-source-annotations.js`
 * 2. Reads `{projectPath}/vite.config.ts`, checks if the plugin is already imported,
 *    and if not, adds the import and plugin reference.
 */
export async function ensureSourceAnnotationsPlugin(
  projectPath: string,
): Promise<void> {
  // Step 1: Write the plugin file
  const doableDir = join(projectPath, ".doable");
  if (!existsSync(doableDir)) {
    await mkdir(doableDir, { recursive: true });
  }

  const pluginFilePath = join(doableDir, "vite-plugin-source-annotations.js");
  const nextContent = generateSourceAnnotationsPlugin();
  // Only write when the content differs — an unconditional writeFile bumps
  // mtime, which Vite's config-file watcher interprets as a config change
  // and triggers a "server restarted" cycle. dev-server-start calls us on
  // every Vite spawn, so without this guard the dev server enters an
  // infinite restart loop and exits with code 1, failing /scaffold.
  // (BUG-R11-VITE-RESTART-LOOP.)
  let prevContent: string | null = null;
  if (existsSync(pluginFilePath)) {
    try {
      prevContent = await readFile(pluginFilePath, "utf-8");
    } catch {
      prevContent = null;
    }
  }
  if (prevContent !== nextContent) {
    await writeFile(pluginFilePath, nextContent, "utf-8");
  }

  // Step 2: Patch vite.config.ts if needed
  const viteConfigPath = join(projectPath, "vite.config.ts");
  if (!existsSync(viteConfigPath)) {
    // No vite config — nothing to patch
    return;
  }

  let viteConfig = await readFile(viteConfigPath, "utf-8");

  // Check if already imported
  if (viteConfig.includes("doable-source-annotations") || viteConfig.includes("vite-plugin-source-annotations")) {
    return;
  }

  // Add the import at the top (after existing imports)
  const importLine = `import doableSourceAnnotations from "./.doable/vite-plugin-source-annotations.js";\n`;

  // Find the last import statement to insert after it
  const importRegex = /^import\s.+$/gm;
  let lastImportEnd = 0;
  let importMatch: RegExpExecArray | null;
  while ((importMatch = importRegex.exec(viteConfig)) !== null) {
    lastImportEnd = importMatch.index + importMatch[0].length;
  }

  if (lastImportEnd > 0) {
    // Insert after the last import
    viteConfig =
      viteConfig.slice(0, lastImportEnd) +
      "\n" +
      importLine +
      viteConfig.slice(lastImportEnd);
  } else {
    // No imports found — add at the very top
    viteConfig = importLine + "\n" + viteConfig;
  }

  // Add the plugin to the plugins array
  // Look for `plugins: [` pattern and insert at the beginning of the array
  const pluginsArrayRegex = /plugins\s*:\s*\[/;
  const pluginsMatch = pluginsArrayRegex.exec(viteConfig);

  if (pluginsMatch) {
    const insertPos = pluginsMatch.index + pluginsMatch[0].length;
    viteConfig =
      viteConfig.slice(0, insertPos) +
      "\n    doableSourceAnnotations()," +
      viteConfig.slice(insertPos);
  }

  await writeFile(viteConfigPath, viteConfig, "utf-8");
}
