/**
 * Vite Plugin: Source Annotations
 *
 * Injects `data-source="filepath:line:col"` attributes into JSX elements
 * at compile time. This allows the visual editor to map DOM elements back
 * to their source code location for click-to-edit functionality.
 *
 * The plugin code is generated as a JS string and written into each
 * project's `.doable/` directory, then referenced from vite.config.ts.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { existsSync } from "node:fs";

// ─── Plugin Code Generator ──────────────────────────────

/**
 * Returns the JavaScript source for the Vite plugin that will be
 * written to each project's `.doable/vite-plugin-source-annotations.js`.
 */
export function generateSourceAnnotationsPlugin(): string {
  return `// Auto-generated by Doable — do not edit manually.
// This Vite plugin injects data-source attributes into JSX elements
// so the visual editor can map DOM elements back to source code.

/**
 * @returns {import('vite').Plugin}
 */
export default function doableSourceAnnotations() {
  let projectRoot = "";

  return {
    name: "doable-source-annotations",
    enforce: "pre",

    configResolved(config) {
      projectRoot = config.root;
    },

    transform(code, id) {
      // Only run in development mode
      if (this.environment?.mode !== "development" && process.env.NODE_ENV === "production") {
        return null;
      }

      // Only process JSX/TSX files
      if (!/\\.[jt]sx$/.test(id)) {
        return null;
      }

      // Skip node_modules and .doable directory
      if (id.includes("node_modules") || id.includes(".doable")) {
        return null;
      }

      // Compute file path relative to project root
      let relPath = id;
      if (projectRoot && id.startsWith(projectRoot)) {
        relPath = id.slice(projectRoot.length);
        // Remove leading slash/backslash
        relPath = relPath.replace(/^[\\\\/]/, "");
      }
      // Normalize to forward slashes
      relPath = relPath.replace(/\\\\/g, "/");

      return transformJsx(code, relPath);
    },
  };
}

/**
 * Regex-based JSX transform that adds data-source attributes.
 *
 * Strategy:
 * 1. Split code into lines to track line numbers.
 * 2. Walk through each character, tracking whether we are inside
 *    a string literal, template literal, or comment.
 * 3. When we find a JSX opening tag (< followed by a valid tag name),
 *    insert data-source after the tag name.
 *
 * This is intentionally simple — it doesn't need to be perfect,
 * just good enough for dev-time source mapping.
 */
function transformJsx(code, filePath) {
  const lines = code.split("\\n");
  const result = [];
  let lineNum = 0;

  for (const line of lines) {
    lineNum++;
    result.push(processLine(line, filePath, lineNum));
  }

  return {
    code: result.join("\\n"),
    map: null, // sourcemap not needed for dev annotations
  };
}

/**
 * Process a single line, injecting data-source attributes into JSX tags.
 * Skips tags that appear inside string literals or comments.
 */
function processLine(line, filePath, lineNum) {
  // Skip lines that are purely comments
  const trimmed = line.trim();
  if (trimmed.startsWith("//") || trimmed.startsWith("*") || trimmed.startsWith("/*")) {
    return line;
  }

  // Match JSX opening tags:
  //   <Component   <div   <MyComponent.Sub   <ns:tag
  // But NOT:
  //   </closing>   <=comparison   <<bitshift   <T>(generic)
  //
  // The regex captures:
  //   Group 1: the full tag name (e.g., "div", "Component", "My.Sub")
  //   The match starts with < and a letter (uppercase or lowercase)
  //
  // We insert data-source after the tag name.
  const tagRegex = /<([A-Z][a-zA-Z0-9.]*|[a-z][a-zA-Z0-9-]*)(?=[\\s/>]|$)/g;

  let output = "";
  let lastIndex = 0;
  let match;

  while ((match = tagRegex.exec(line)) !== null) {
    const matchStart = match.index;
    const tagName = match[1];
    const afterTagName = matchStart + match[0].length;

    // Column is 1-based
    const col = matchStart + 1;

    // Skip if this looks like it's inside a string
    if (isInsideString(line, matchStart)) {
      continue;
    }

    // Skip closing tags — check if there's a / before the tag name
    if (matchStart > 0 && line[matchStart + 1] === "/") {
      continue;
    }

    // Skip certain tags that shouldn't get annotations
    // (fragments, generic type params, etc.)
    if (tagName === "T" || tagName === "K" || tagName === "V" || tagName === "P") {
      // Likely a generic type parameter — skip single uppercase letters
      // unless followed by a space and attributes (heuristic)
      const after = line[afterTagName];
      if (after === ">" || after === ",") {
        continue;
      }
    }

    const sourceAttr = \` data-source="\${filePath}:\${lineNum}:\${col}"\`;

    // Append everything up to after the tag name, then the attribute
    output += line.slice(lastIndex, afterTagName);
    output += sourceAttr;
    lastIndex = afterTagName;
  }

  // Append the rest of the line
  output += line.slice(lastIndex);

  return output;
}

/**
 * Simple heuristic to detect if a position is inside a string literal.
 * Counts unescaped quotes before the position.
 */
function isInsideString(line, pos) {
  let inSingle = false;
  let inDouble = false;
  let inTemplate = false;

  for (let i = 0; i < pos; i++) {
    const ch = line[i];
    const prev = i > 0 ? line[i - 1] : "";

    if (prev === "\\\\") continue; // escaped character

    if (ch === "'" && !inDouble && !inTemplate) {
      inSingle = !inSingle;
    } else if (ch === '"' && !inSingle && !inTemplate) {
      inDouble = !inDouble;
    } else if (ch === "\\\`" && !inSingle && !inDouble) {
      inTemplate = !inTemplate;
    }
  }

  return inSingle || inDouble || inTemplate;
}
`;
}

// ─── Plugin Installation ─────────────────────────────────

/**
 * Ensure the source annotations plugin is installed in a project.
 *
 * 1. Writes the plugin JS file to `{projectPath}/.doable/vite-plugin-source-annotations.js`
 * 2. Reads `{projectPath}/vite.config.ts`, checks if the plugin is already imported,
 *    and if not, adds the import and plugin reference.
 */
export async function ensureSourceAnnotationsPlugin(
  projectPath: string,
): Promise<void> {
  // Step 1: Write the plugin file
  const doableDir = join(projectPath, ".doable");
  if (!existsSync(doableDir)) {
    await mkdir(doableDir, { recursive: true });
  }

  const pluginFilePath = join(doableDir, "vite-plugin-source-annotations.js");
  await writeFile(pluginFilePath, generateSourceAnnotationsPlugin(), "utf-8");

  // Step 2: Patch vite.config.ts if needed
  const viteConfigPath = join(projectPath, "vite.config.ts");
  if (!existsSync(viteConfigPath)) {
    // No vite config — nothing to patch
    return;
  }

  let viteConfig = await readFile(viteConfigPath, "utf-8");

  // Check if already imported
  if (viteConfig.includes("doable-source-annotations") || viteConfig.includes("vite-plugin-source-annotations")) {
    return;
  }

  // Add the import at the top (after existing imports)
  const importLine = `import doableSourceAnnotations from "./.doable/vite-plugin-source-annotations.js";\n`;

  // Find the last import statement to insert after it
  const importRegex = /^import\s.+$/gm;
  let lastImportEnd = 0;
  let importMatch: RegExpExecArray | null;
  while ((importMatch = importRegex.exec(viteConfig)) !== null) {
    lastImportEnd = importMatch.index + importMatch[0].length;
  }

  if (lastImportEnd > 0) {
    // Insert after the last import
    viteConfig =
      viteConfig.slice(0, lastImportEnd) +
      "\n" +
      importLine +
      viteConfig.slice(lastImportEnd);
  } else {
    // No imports found — add at the very top
    viteConfig = importLine + "\n" + viteConfig;
  }

  // Add the plugin to the plugins array
  // Look for `plugins: [` pattern and insert at the beginning of the array
  const pluginsArrayRegex = /plugins\s*:\s*\[/;
  const pluginsMatch = pluginsArrayRegex.exec(viteConfig);

  if (pluginsMatch) {
    const insertPos = pluginsMatch.index + pluginsMatch[0].length;
    viteConfig =
      viteConfig.slice(0, insertPos) +
      "\n    doableSourceAnnotations()," +
      viteConfig.slice(insertPos);
  }

  await writeFile(viteConfigPath, viteConfig, "utf-8");
}
