#!/usr/bin/env bash
# ==============================================================================
# Doable — Self-hosting setup script
# ==============================================================================
# Sets up everything needed to run Doable with Docker Compose + nginx + SSL.
#
# Usage:
#   # Interactive:
#   ./docker/setup.sh
#
#   # One-liner with domain:
#   DOMAIN=app.example.com ./docker/setup.sh
#
#   # Localhost only (no nginx/SSL):
#   ./docker/setup.sh --local
# ==============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$SCRIPT_DIR/.env"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()  { echo -e "${BLUE}[info]${NC}  $*"; }
ok()    { echo -e "${GREEN}[ok]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC}  $*"; }
error() { echo -e "${RED}[error]${NC} $*" >&2; }

# ─── Parse args ───────────────────────────────────────────────────────────────
LOCAL_ONLY=false
SKIP_SSL=false
for arg in "$@"; do
  case "$arg" in
    --local)     LOCAL_ONLY=true ;;
    --skip-ssl)  SKIP_SSL=true ;;
    --help|-h)
      echo "Usage: [DOMAIN=app.example.com] $0 [--local] [--skip-ssl]"
      echo ""
      echo "Options:"
      echo "  --local      Skip nginx/SSL, run on localhost only"
      echo "  --skip-ssl   Set up nginx but skip Let's Encrypt (e.g. behind CloudFlare)"
      echo ""
      echo "Environment variables:"
      echo "  DOMAIN       Your domain name (e.g. app.example.com)"
      echo "  EMAIL        Email for Let's Encrypt notifications"
      exit 0
      ;;
  esac
done

# ─── Check prerequisites ─────────────────────────────────────────────────────
info "Checking prerequisites..."

if ! command -v docker &>/dev/null; then
  error "Docker is not installed. Install it from https://docs.docker.com/engine/install/"
  exit 1
fi

if ! docker compose version &>/dev/null; then
  error "Docker Compose v2 is required. Install it from https://docs.docker.com/compose/install/"
  exit 1
fi

ok "Docker and Docker Compose found"

# ─── Determine domain ────────────────────────────────────────────────────────
if [ "$LOCAL_ONLY" = true ]; then
  DOMAIN=""
  info "Local mode — skipping domain/nginx/SSL setup"
elif [ -z "${DOMAIN:-}" ]; then
  echo ""
  read -rp "Enter your domain name (e.g. app.example.com), or press Enter for localhost: " DOMAIN
fi

# ─── Generate .env ────────────────────────────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
  warn ".env already exists at $ENV_FILE"
  read -rp "Overwrite? [y/N] " overwrite
  if [[ ! "$overwrite" =~ ^[Yy] ]]; then
    info "Keeping existing .env"
  else
    rm "$ENV_FILE"
  fi
fi

if [ ! -f "$ENV_FILE" ]; then
  info "Generating docker/.env with random secrets..."

  JWT_SECRET=$(openssl rand -hex 32)
  ENCRYPTION_KEY=$(openssl rand -hex 32)
  INTERNAL_SECRET=$(openssl rand -hex 32)
  PG_PASSWORD=$(openssl rand -hex 16)

  if [ -n "$DOMAIN" ]; then
    API_URL="https://${DOMAIN}/api"
    WS_URL="wss://${DOMAIN}/ws"
    APP_URL="https://${DOMAIN}"
    CORS="https://${DOMAIN}"
  else
    API_URL="http://localhost:4000"
    WS_URL="ws://localhost:4001"
    APP_URL="http://localhost:3000"
    CORS="http://localhost:3000"
  fi

  cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Domain: ${DOMAIN:-localhost}

# ─── Secrets ───────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
INTERNAL_SECRET=${INTERNAL_SECRET}

# ─── Database ──────────────────────────────────────
POSTGRES_USER=doable
POSTGRES_PASSWORD=${PG_PASSWORD}
POSTGRES_DB=doable

# ─── URLs ──────────────────────────────────────────
NEXT_PUBLIC_API_URL=${API_URL}
NEXT_PUBLIC_WS_URL=${WS_URL}
NEXT_PUBLIC_APP_URL=${APP_URL}
CORS_ORIGINS=${CORS}

# ─── Redis (optional) ─────────────────────────────
REDIS_URL=

# ─── AI (set at least one for AI features) ────────
ANTHROPIC_API_KEY=
OPENAI_API_KEY=

# ─── OAuth (optional) ─────────────────────────────
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# ─── Stripe (optional) ────────────────────────────
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
EOF

  ok "Created docker/.env with generated secrets"
fi

# ─── Set up nginx + SSL ──────────────────────────────────────────────────────
if [ -n "$DOMAIN" ] && [ "$LOCAL_ONLY" = false ]; then
  info "Setting up nginx reverse proxy for ${DOMAIN}..."

  # Install nginx + certbot if not present
  if ! command -v nginx &>/dev/null; then
    info "Installing nginx and certbot..."
    apt-get update -qq
    apt-get install -y -qq nginx certbot python3-certbot-nginx
    ok "Installed nginx and certbot"
  fi

  # Generate nginx config from template
  NGINX_CONF="/etc/nginx/sites-available/${DOMAIN}"
  sed "s/__DOMAIN__/${DOMAIN}/g" "$SCRIPT_DIR/nginx.conf.template" > "$NGINX_CONF"

  # Enable site
  ln -sf "$NGINX_CONF" "/etc/nginx/sites-enabled/${DOMAIN}"
  rm -f /etc/nginx/sites-enabled/default

  if [ "$SKIP_SSL" = false ]; then
    # Start with HTTP-only config for cert issuance
    cat > "$NGINX_CONF" <<HTTPEOF
server {
    listen 80;
    server_name ${DOMAIN};
    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / { return 301 https://\$host\$request_uri; }
}
HTTPEOF
    nginx -t && systemctl reload nginx

    # Get SSL certificate
    EMAIL_FLAG=""
    if [ -n "${EMAIL:-}" ]; then
      EMAIL_FLAG="-m $EMAIL"
    else
      EMAIL_FLAG="--register-unsafely-without-email"
    fi

    info "Requesting Let's Encrypt certificate for ${DOMAIN}..."
    certbot certonly --webroot -w /var/www/html -d "$DOMAIN" $EMAIL_FLAG --agree-tos --non-interactive

    # Now write the full config with SSL
    sed "s/__DOMAIN__/${DOMAIN}/g" "$SCRIPT_DIR/nginx.conf.template" > "$NGINX_CONF"
    ok "SSL certificate obtained"
  else
    info "Skipping SSL (--skip-ssl). Configure certificates manually."
  fi

  nginx -t && systemctl reload nginx
  ok "nginx configured and running for ${DOMAIN}"

  # Open firewall ports
  if command -v ufw &>/dev/null; then
    ufw allow 22/tcp >/dev/null 2>&1 || true
    ufw allow 80/tcp >/dev/null 2>&1 || true
    ufw allow 443/tcp >/dev/null 2>&1 || true
    ufw --force enable >/dev/null 2>&1 || true
    ok "Firewall: ports 22, 80, 443 open"
  fi
fi

# ─── Build and start ─────────────────────────────────────────────────────────
echo ""
info "Building and starting Docker containers..."
cd "$PROJECT_DIR"
docker compose -f "$COMPOSE_FILE" build
docker compose -f "$COMPOSE_FILE" up -d

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [ -n "$DOMAIN" ]; then
  echo -e "${GREEN}Doable is running at https://${DOMAIN}${NC}"
else
  echo -e "${GREEN}Doable is running at http://localhost:3000${NC}"
fi
echo ""
echo "  Dashboard:  ${APP_URL:-http://localhost:3000}"
echo "  API:        ${API_URL:-http://localhost:4000}/health"
echo ""
echo "  Edit config: docker/.env"
echo "  View logs:   docker compose -f docker/docker-compose.yml logs -f"
echo "  Stop:        docker compose -f docker/docker-compose.yml down"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
