import type { IntegrationDefinition } from "../types.js";

// ─── Google OAuth2 Shared Config ────────────────────────
const GOOGLE_AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth";
const GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token";
const GOOGLE_OAUTH_BASE = {
  authUrl: GOOGLE_AUTH_URL,
  tokenUrl: GOOGLE_TOKEN_URL,
  // PKCE not needed for confidential clients (server-side with client_secret)
  prompt: "consent" as const,
  extraParams: { access_type: "offline" },
};

// ─── Atlassian OAuth2 Shared Config ─────────────────────
const ATLASSIAN_AUTH_URL = "https://auth.atlassian.com/authorize";
const ATLASSIAN_TOKEN_URL = "https://auth.atlassian.com/oauth/token";

// ─── Productivity, Project Management & Collaboration ───

export const PRODUCTIVITY_INTEGRATIONS: Record<string, IntegrationDefinition> = {

  // ── Google Suite ──────────────────────────────────────

  google_docs: {
    id: "google_docs",
    piecePackage: "@activepieces/piece-google-docs",
    displayName: "Google Docs",
    description: "Create and edit documents in Google Docs.",
    logoUrl: "https://cdn.activepieces.com/pieces/google-docs.png",
    category: "productivity",
    tags: ["google", "documents", "writing", "docs"],
    authType: "oauth2",
    oauth2Config: {
      ...GOOGLE_OAUTH_BASE,
      scopes: ["https://www.googleapis.com/auth/documents"],
    },
    actions: ["create_document", "get_document", "append_text"],
    tier: "built_in",
    requiresOAuthApp: true,
    supportsUserProvidedCredentials: true,
  },

  google_calendar: {
    id: "google_calendar",
    piecePackage: "@activepieces/piece-google-calendar",
    displayName: "Google Calendar",
    description: "Create events, check availability, and manage your Google Calendar.",
    logoUrl: "https://cdn.activepieces.com/pieces/google-calendar.png",
    category: "productivity",
    tags: ["google", "calendar", "events", "scheduling"],
    authType: "oauth2",
    oauth2Config: {
      ...GOOGLE_OAUTH_BASE,
      scopes: ["https://www.googleapis.com/auth/calendar.events"],
    },
    actions: ["create_event", "list_events", "update_event", "delete_event", "find_free_time"],
    tier: "built_in",
    requiresOAuthApp: true,
    supportsUserProvidedCredentials: true,
  },

  google_drive: {
    id: "google_drive",
    piecePackage: "@activepieces/piece-google-drive",
    displayName: "Google Drive",
    description: "Upload files, create folders, and manage content in Google Drive.",
    logoUrl: "https://cdn.activepieces.com/pieces/google-drive.png",
    category: "productivity",
    tags: ["google", "drive", "files", "storage", "cloud"],
    authType: "oauth2",
    oauth2Config: {
      ...GOOGLE_OAUTH_BASE,
      scopes: ["https://www.googleapis.com/auth/drive"],
    },
    actions: ["upload_file", "create_folder", "list_files", "search-folder", "read-file"],
    tier: "built_in",
    requiresOAuthApp: true,
    supportsUserProvidedCredentials: true,
  },

  google_contacts: {
    id: "google_contacts",
    piecePackage: "@activepieces/piece-google-contacts",
    displayName: "Google Contacts",
    description: "Create, list, and search contacts in Google Contacts.",
    logoUrl: "https://cdn.activepieces.com/pieces/google-contacts.png",
    category: "productivity",
    tags: ["google", "contacts", "address-book", "people"],
    authType: "oauth2",
    oauth2Config: {
      ...GOOGLE_OAUTH_BASE,
      scopes: ["https://www.googleapis.com/auth/contacts"],
    },
    actions: ["create_contact", "find-contact", "create-contact"],
    tier: "built_in",
    requiresOAuthApp: true,
    supportsUserProvidedCredentials: true,
  },

  google_forms: {
    id: "google_forms",
    piecePackage: "@activepieces/piece-google-forms",
    displayName: "Google Forms",
    description: "Read form definitions and list responses from Google Forms.",
    logoUrl: "https://cdn.activepieces.com/pieces/google-forms.png",
    category: "productivity",
    tags: ["google", "forms", "surveys", "responses"],
    authType: "oauth2",
    oauth2Config: {
      ...GOOGLE_OAUTH_BASE,
      scopes: ["https://www.googleapis.com/auth/forms.body.readonly"],
    },
    actions: ["get_form", "list_responses"],
    tier: "built_in",
    requiresOAuthApp: true,
    supportsUserProvidedCredentials: true,
  },

  google_tasks: {
    id: "google_tasks",
    piecePackage: "@activepieces/piece-google-tasks",
    displayName: "Google Tasks",
    description: "Create, list, and manage tasks in Google Tasks.",
    logoUrl: "https://cdn.activepieces.com/pieces/google-tasks.png",
    category: "productivity",
    tags: ["google", "tasks", "todo", "checklist"],
    authType: "oauth2",
    oauth2Config: {
      ...GOOGLE_OAUTH_BASE,
      scopes: ["https://www.googleapis.com/auth/tasks"],
    },
    actions: ["create_task", "add_task", "update_task"],
    tier: "built_in",
    requiresOAuthApp: true,
    supportsUserProvidedCredentials: true,
  },

  // ── Productivity / Databases ──────────────────────────

  airtable: {
    id: "airtable",
    piecePackage: "@activepieces/piece-airtable",
    displayName: "Airtable",
    description: "Create, find, update, and delete records in Airtable bases.",
    logoUrl: "https://cdn.activepieces.com/pieces/airtable.png",
    category: "productivity",
    tags: ["database", "spreadsheet", "nocode", "records"],
    authType: "secret_text",
    actions: ["create_record", "find_record", "update_record", "delete_record", "find_record"],
    tier: "built_in",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  monday: {
    id: "monday",
    piecePackage: "@activepieces/piece-monday",
    displayName: "monday.com",
    description: "Create and update items, list boards, and post updates in monday.com.",
    logoUrl: "https://cdn.activepieces.com/pieces/monday.png",
    category: "productivity",
    tags: ["project-management", "boards", "tasks", "work-os"],
    authType: "secret_text",
    actions: ["create_item", "update_item", "list_boards", "list_items", "monday_create_update"],
    tier: "built_in",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  asana: {
    id: "asana",
    piecePackage: "@activepieces/piece-asana",
    displayName: "Asana",
    description: "Create tasks, manage projects, and collaborate in Asana.",
    logoUrl: "https://cdn.activepieces.com/pieces/asana.png",
    category: "productivity",
    tags: ["project-management", "tasks", "collaboration", "team"],
    authType: "oauth2",
    oauth2Config: {
      authUrl: "https://app.asana.com/-/oauth_authorize",
      tokenUrl: "https://app.asana.com/-/oauth_token",
      scopes: ["default"],
    },
    actions: ["create_task", "update_task", "find_task", "create_project", "add_comment"],
    tier: "built_in",
    requiresOAuthApp: true,
    supportsUserProvidedCredentials: true,
  },

  clickup: {
    id: "clickup",
    piecePackage: "@activepieces/piece-clickup",
    displayName: "ClickUp",
    description: "Create and manage tasks, lists, and comments in ClickUp.",
    logoUrl: "https://cdn.activepieces.com/pieces/clickup.png",
    category: "productivity",
    tags: ["project-management", "tasks", "collaboration"],
    authType: "secret_text",
    actions: ["create_task", "update_task", "get_task", "create_card", "add_comment"],
    tier: "built_in",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  trello: {
    id: "trello",
    piecePackage: "@activepieces/piece-trello",
    displayName: "Trello",
    description: "Create cards, manage lists, and add comments in Trello boards.",
    logoUrl: "https://cdn.activepieces.com/pieces/trello.png",
    category: "productivity",
    tags: ["kanban", "boards", "cards", "project-management"],
    authType: "secret_text",
    actions: ["create_card", "update_card", "get_card", "create_list", "add_comment"],
    tier: "built_in",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  todoist: {
    id: "todoist",
    piecePackage: "@activepieces/piece-todoist",
    displayName: "Todoist",
    description: "Create, update, and complete tasks in Todoist.",
    logoUrl: "https://cdn.activepieces.com/pieces/todoist.png",
    category: "productivity",
    tags: ["tasks", "todo", "personal-productivity", "gtd"],
    authType: "secret_text",
    actions: ["create_task", "update_task", "find_task", "complete_task", "list_projects"],
    tier: "built_in",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  coda: {
    id: "coda",
    piecePackage: "@activepieces/piece-coda",
    displayName: "Coda",
    description: "Create rows, list tables, and manage data in Coda docs.",
    logoUrl: "https://cdn.activepieces.com/pieces/coda.png",
    category: "productivity",
    tags: ["docs", "tables", "database", "collaborative"],
    authType: "secret_text",
    actions: ["create_row", "find-row", "update_row", "list-tables"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  baserow: {
    id: "baserow",
    piecePackage: "@activepieces/piece-baserow",
    displayName: "Baserow",
    description: "Create, list, update, and delete rows in Baserow databases.",
    logoUrl: "https://cdn.activepieces.com/pieces/baserow.png",
    category: "productivity",
    tags: ["database", "open-source", "nocode", "airtable-alternative"],
    authType: "secret_text",
    actions: ["create_row", "upsert_row", "update_row", "delete_row"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  nocodb: {
    id: "nocodb",
    piecePackage: "@activepieces/piece-nocodb",
    displayName: "NocoDB",
    description: "Create, list, and update records in NocoDB databases.",
    logoUrl: "https://cdn.activepieces.com/pieces/nocodb.png",
    category: "productivity",
    tags: ["database", "open-source", "nocode", "airtable-alternative"],
    authType: "secret_text",
    actions: ["create_record", "find_record", "update_record"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  // ── Project Management ────────────────────────────────

  linear: {
    id: "linear",
    piecePackage: "@activepieces/piece-linear",
    displayName: "Linear",
    description: "Create issues, list teams, and manage projects in Linear.",
    logoUrl: "https://cdn.activepieces.com/pieces/linear.png",
    category: "project_management",
    tags: ["issues", "project-management", "engineering", "agile"],
    authType: "oauth2",
    oauth2Config: {
      authUrl: "https://linear.app/oauth/authorize",
      tokenUrl: "https://api.linear.app/oauth/token",
      scopes: ["read", "write"],
    },
    actions: ["create_issue", "update_issue", "find_issue", "create_comment", "list_teams"],
    tier: "built_in",
    requiresOAuthApp: true,
    supportsUserProvidedCredentials: true,
  },

  jira_cloud: {
    id: "jira_cloud",
    piecePackage: "@activepieces/piece-jira-cloud",
    displayName: "Jira Cloud",
    description: "Create and search issues, add comments, and manage projects in Jira.",
    logoUrl: "https://cdn.activepieces.com/pieces/jira.png",
    category: "project_management",
    tags: ["issues", "project-management", "agile", "atlassian"],
    authType: "oauth2",
    oauth2Config: {
      authUrl: ATLASSIAN_AUTH_URL,
      tokenUrl: ATLASSIAN_TOKEN_URL,
      scopes: ["read:jira-work", "write:jira-work"],
    },
    actions: ["create_issue", "update_issue", "search_issues", "add_comment", "list_projects"],
    tier: "built_in",
    requiresOAuthApp: true,
    supportsUserProvidedCredentials: true,
  },

  confluence: {
    id: "confluence",
    piecePackage: "@activepieces/piece-confluence",
    displayName: "Confluence",
    description: "Create pages, search content, and manage knowledge bases in Confluence.",
    logoUrl: "https://cdn.activepieces.com/pieces/confluence.png",
    category: "project_management",
    tags: ["wiki", "docs", "knowledge-base", "atlassian"],
    authType: "oauth2",
    oauth2Config: {
      authUrl: ATLASSIAN_AUTH_URL,
      tokenUrl: ATLASSIAN_TOKEN_URL,
      scopes: ["read:confluence-content.all", "write:confluence-content"],
    },
    actions: ["create_page", "update_page", "getPageContent", "get_page"],
    tier: "built_in",
    requiresOAuthApp: true,
    supportsUserProvidedCredentials: true,
  },

  productboard: {
    id: "productboard",
    piecePackage: "@activepieces/piece-productboard",
    displayName: "Productboard",
    description: "Create notes and manage features in Productboard.",
    logoUrl: "https://cdn.activepieces.com/pieces/productboard.png",
    category: "project_management",
    tags: ["product", "roadmap", "features", "feedback"],
    authType: "secret_text",
    actions: ["create_note", "list_features", "create_feature"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  height: {
    id: "height",
    piecePackage: "@activepieces/piece-height",
    displayName: "Height",
    description: "Create, list, and update tasks in Height.",
    logoUrl: "https://cdn.activepieces.com/pieces/height.png",
    category: "project_management",
    tags: ["tasks", "project-management", "team"],
    authType: "secret_text",
    actions: ["create_task", "list_tasks", "update_task"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  // ── Time Tracking ─────────────────────────────────────

  clockify: {
    id: "clockify",
    piecePackage: "@activepieces/piece-clockify",
    displayName: "Clockify",
    description: "Create time entries and list projects in Clockify.",
    logoUrl: "https://cdn.activepieces.com/pieces/clockify.png",
    category: "project_management",
    tags: ["time-tracking", "timesheets", "productivity"],
    authType: "secret_text",
    actions: ["create_time_entry", "find-time-entry", "list_projects"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  everhour: {
    id: "everhour",
    piecePackage: "@activepieces/piece-everhour",
    displayName: "Everhour",
    description: "Track time and list tasks in Everhour.",
    logoUrl: "https://cdn.activepieces.com/pieces/everhour.png",
    category: "project_management",
    tags: ["time-tracking", "timesheets", "budgeting"],
    authType: "secret_text",
    actions: ["create_time_entry", "list_tasks"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  harvest: {
    id: "harvest",
    piecePackage: "@activepieces/piece-harvest",
    displayName: "Harvest",
    description: "Create and list time entries in Harvest.",
    logoUrl: "https://cdn.activepieces.com/pieces/harvest.png",
    category: "project_management",
    tags: ["time-tracking", "invoicing", "timesheets"],
    authType: "secret_text",
    actions: ["create_time_entry", "get_time_entries"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  toggl_track: {
    id: "toggl_track",
    piecePackage: "@activepieces/piece-toggl",
    displayName: "Toggl Track",
    description: "Create time entries and list projects in Toggl Track.",
    logoUrl: "https://cdn.activepieces.com/pieces/toggl.png",
    category: "project_management",
    tags: ["time-tracking", "timesheets", "productivity"],
    authType: "secret_text",
    actions: ["create_time_entry", "list_time_entries", "list_projects"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  // ── Task Management ───────────────────────────────────

  ticktick: {
    id: "ticktick",
    piecePackage: "@activepieces/piece-ticktick",
    displayName: "TickTick",
    description: "Create, list, and complete tasks in TickTick.",
    logoUrl: "https://cdn.activepieces.com/pieces/ticktick.png",
    category: "productivity",
    tags: ["tasks", "todo", "habits", "personal-productivity"],
    authType: "secret_text",
    actions: ["create_task", "list_tasks", "complete_task"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  meistertask: {
    id: "meistertask",
    piecePackage: "@activepieces/piece-meistertask",
    displayName: "MeisterTask",
    description: "Create, list, and update tasks in MeisterTask.",
    logoUrl: "https://cdn.activepieces.com/pieces/meistertask.png",
    category: "productivity",
    tags: ["tasks", "kanban", "project-management"],
    authType: "secret_text",
    actions: ["create_task", "list_tasks", "update_task"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  taskade: {
    id: "taskade",
    piecePackage: "@activepieces/piece-taskade",
    displayName: "Taskade",
    description: "Create and list tasks in Taskade workspaces.",
    logoUrl: "https://cdn.activepieces.com/pieces/taskade.png",
    category: "productivity",
    tags: ["tasks", "collaboration", "notes", "ai"],
    authType: "secret_text",
    actions: ["create_task", "list_tasks"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },

  nifty: {
    id: "nifty",
    piecePackage: "@activepieces/piece-nifty",
    displayName: "Nifty",
    description: "Create and list tasks in Nifty project management.",
    logoUrl: "https://cdn.activepieces.com/pieces/nifty.png",
    category: "productivity",
    tags: ["project-management", "tasks", "collaboration"],
    authType: "secret_text",
    actions: ["create_task", "list_tasks"],
    tier: "community",
    requiresOAuthApp: false,
    supportsUserProvidedCredentials: true,
  },
};
