import type { FrameworkPrompt } from "./index.js";

export const astroPrompt: FrameworkPrompt = {
  systemIntro:
    "The project is an Astro + TypeScript site with Tailwind CSS v4. Astro is a content-focused framework that ships zero JavaScript by default. It uses file-based routing and supports multiple UI frameworks (React, Svelte, Vue) as islands of interactivity.",

  envConventions: [
    "0. **🔌 USE CONNECTED INTEGRATIONS**: If a `<connected-integrations>` block appears above, use the listed env vars and tools. NEVER ask for API keys.",
    "",
    "0a. **ENV VAR RULES (Astro)**:",
    "   - Server-only secrets: access via `import.meta.env.X` in `.astro` files (frontmatter), API routes, and middleware. These are available at build time and in SSR mode.",
    "   - Browser-safe values: must be prefixed with `PUBLIC_` — e.g. `import.meta.env.PUBLIC_API_URL`.",
    "   - NEVER put secrets in `PUBLIC_*` vars.",
    "",
    "0b. **🔌 SUPABASE NOT CONNECTED?** Call `provision_supabase` first.",
    "",
    "1. **SUPABASE PATTERNS (Astro)**:",
    "   - In .astro frontmatter or API routes: `import.meta.env.SUPABASE_SERVICE_ROLE_KEY`",
    "   - In client-side scripts (island components): use `PUBLIC_SUPABASE_URL` + anon key only.",
  ].join("\n"),

  routing: [
    "2. **FILE-BASED ROUTING**: Astro uses `src/pages/`.",
    "   - `src/pages/index.astro` → `/`",
    "   - `src/pages/about.astro` → `/about`",
    "   - `src/pages/blog/[slug].astro` → `/blog/:slug`",
    "   - `src/layouts/Layout.astro` — layout components (imported manually, not auto-detected)",
    "   - API routes: `src/pages/api/items.ts` exporting `GET`, `POST` handlers (SSR mode only).",
    "   - Static pages: default. For dynamic pages, add `export const prerender = false;`",
    "   - Use `<a href=\"/path\">` for navigation (no client-side router by default).",
    "",
    "2a. **CRITICAL: Client-side fetch URLs MUST be RELATIVE.**",
    "   The preview iframe runs at `/preview/<projectId>/`, so any absolute path",
    "   that begins with `/` resolves against Doable's API host (which 404s),",
    "   NOT against your Astro site. This trap only applies to code that runs",
    "   in the browser — `.astro` frontmatter and API route handlers run in Node",
    "   and may use absolute paths freely.",
    "   Browser-side surfaces this affects: client islands (any component using",
    "   `client:load` / `client:visible` / `client:idle` / `client:only`) and",
    "   inline `<script>` blocks calling `src/pages/api/*` endpoints.",
    "   Allowed patterns:",
    "   - Relative path: `fetch(\"./api/items\")` or `fetch(\"api/items\")` (current page-relative).",
    "   - BASE_URL prefix: `fetch(\\`${import.meta.env.BASE_URL}api/items\\`)` — works when site is deployed under a sub-path.",
    "   - For data the page already has at build/SSR time, prefer reading it in `.astro` frontmatter and passing it as a prop to the island instead of refetching client-side.",
    "   NEVER write `fetch(\"/api/items\")` in island components or inline `<script>` blocks — it WILL break in preview.",
  ].join("\n"),

  styling: [
    "6. **TAILWIND CSS v4 (Astro)** — Via `@tailwindcss/vite` integration:",
    "   - Global CSS in `src/styles/global.css`: `@import \"tailwindcss\";`",
    "   - Import from layout: `import '../styles/global.css';` in Layout.astro frontmatter.",
    "   - NEVER use v3 directives or `@apply`. NEVER create tailwind.config files.",
    "   - Scoped styles: use `<style>` in .astro files (scoped by default).",
  ].join("\n"),

  fileShape: [
    "7. **ASTRO COMPONENTS**: `.astro` files have a frontmatter fence (---) and HTML template:",
    "   ```astro",
    "   ---",
    "   const title = 'Hello';",
    "   const items = await fetch('/api/items').then(r => r.json());",
    "   ---",
    "   <h1>{title}</h1>",
    "   <ul>{items.map(i => <li>{i.name}</li>)}</ul>",
    "   ```",
    "",
    "8. **ISLANDS ARCHITECTURE**: Interactive components use `client:*` directives:",
    "   - `<Counter client:load />` — hydrates immediately",
    "   - `<Chart client:visible />` — hydrates when visible",
    "   - `<Menu client:idle />` — hydrates on idle",
    "   - Without `client:*`, components render as static HTML (zero JS shipped).",
    "",
    "9. **FRAMEWORK ISLANDS**: You can use React/Svelte/Vue components as islands:",
    "   - Install: `@astrojs/react`, `@astrojs/svelte`, or `@astrojs/vue`",
    "   - Import and use with `client:load` directive for interactivity.",
  ].join("\n"),
};
