import type { FrameworkPrompt } from "./index.js";

export const djangoPrompt: FrameworkPrompt = {
  systemIntro:
    "The project is a Django + Python web application. Django is a full-featured web framework with an ORM, admin panel, auth system, and template engine. The dev server runs via `manage.py runserver`. This is a full-stack framework — it serves both HTML pages and API endpoints.",

  envConventions: [
    "0. **🔌 USE CONNECTED INTEGRATIONS**: If a `<connected-integrations>` block appears above, use the listed env vars. NEVER ask for API keys.",
    "",
    "0a. **ENV VAR RULES (Django)**:",
    "   - ALL env vars are server-only.",
    "   - Access via `os.environ['X']` or `os.getenv('X', default)`.",
    "   - For structured config, use `django-environ` or `python-decouple`.",
    "   - Database: set `DATABASES` in settings.py from `DATABASE_URL` or individual PG* vars.",
    "",
    "1. **DATABASE PATTERNS (Django)**:",
    "   - Django ORM is the primary data layer. Define models in `models.py`.",
    "   - Use `dj-database-url` to parse DATABASE_URL: `DATABASES = {'default': dj_database_url.parse(os.environ['DATABASE_URL'])}`",
    "   - Run migrations: `python manage.py makemigrations && python manage.py migrate`",
    "   - Supabase as PostgreSQL: just use the connection string from `PGHOST`/`PGPORT`/etc.",
  ].join("\n"),

  routing: [
    "2. **DJANGO URL ROUTING**: URLs defined in `urls.py` files.",
    "   - `project/urls.py` → root URL conf",
    "   - `app/urls.py` → per-app URL patterns included via `include()`",
    "   - `path('items/', views.item_list, name='item-list')`",
    "   - `path('items/<int:pk>/', views.item_detail, name='item-detail')`",
    "   - For REST APIs: use Django REST Framework (DRF) with ViewSets and Serializers.",
    "   - For templates: `render(request, 'template.html', context)`",
    "",
    "**Structure:**",
    "   - `manage.py` — Django CLI entry point",
    "   - `project/` — settings, root urls, wsgi/asgi",
    "   - `app/` — models, views, urls, serializers, templates",
    "",
    "2a. **CRITICAL: Client-side fetch URLs MUST be RELATIVE.**",
    "   Django renders templates server-side, but any `fetch()` inside an inline",
    "   `<script>` block runs in the browser inside Doable's preview iframe at",
    "   `/preview/<projectId>/`. Absolute paths starting with `/` hit Doable's",
    "   API host (404), NOT your Django app.",
    "   This trap applies ONLY to JavaScript fetch — server-rendered `<a href=\"/items/\">`",
    "   navigation works fine because the browser resolves links against the iframe's",
    "   own location.",
    "   Allowed patterns:",
    "   - Relative path: `fetch(\"./api/items/\")` from inline `<script>`.",
    "   - `{% url 'view-name' %}` template tag emits the correct prefix-aware path: `fetch(\"{% url 'item-list' %}\")`.",
    "   - Server-side: `request.build_absolute_uri('/api/items/')` returns the full URL with the right host.",
    "   NEVER write `fetch(\"/api/items/\")` in inline `<script>` blocks — it WILL break in preview.",
  ].join("\n"),

  styling: [
    "6. **DJANGO TEMPLATES + TAILWIND**: If using HTML templates:",
    "   - Use Django template language (`{% %}`, `{{ }}`)",
    "   - Include Tailwind via CDN in base template: `<script src=\"https://cdn.tailwindcss.com\"></script>`",
    "   - Or use `django-tailwind` package for build-step integration.",
    "   - For API-only projects, skip templates entirely.",
  ].join("\n"),

  fileShape: [
    "7. **DJANGO PROJECT STRUCTURE**:",
    "   ```",
    "   manage.py",
    "   requirements.txt",
    "   project/",
    "     __init__.py",
    "     settings.py",
    "     urls.py",
    "     wsgi.py",
    "   app/",
    "     __init__.py",
    "     models.py",
    "     views.py",
    "     urls.py",
    "     serializers.py  (if DRF)",
    "     admin.py",
    "     migrations/",
    "   ```",
    "",
    "8. **MODELS**: Define in `app/models.py`. Always run `makemigrations` + `migrate` after model changes.",
    "",
    "9. **SETTINGS**: Keep secrets in env vars, never hardcode. Use `DEBUG = os.getenv('DEBUG', 'False') == 'True'`.",
  ].join("\n"),
};
