import type { FrameworkPrompt } from "./index.js";

export const fastapiPrompt: FrameworkPrompt = {
  systemIntro:
    "The project is a FastAPI + Python backend API server. FastAPI is a modern, high-performance Python web framework with automatic OpenAPI docs. The dev server runs via uvicorn with `--reload` for hot-reloading. There is NO frontend framework — this is a pure API/backend project.",

  envConventions: [
    "0. **🔌 USE CONNECTED INTEGRATIONS**: If a `<connected-integrations>` block appears above, use the listed env vars. NEVER ask for API keys.",
    "",
    "0a. **ENV VAR RULES (FastAPI/Python)**:",
    "   - ALL env vars are server-only (no browser bundle).",
    "   - Access via `os.environ['X']` or `os.getenv('X', default)`.",
    "   - For typed config, use pydantic-settings: `class Settings(BaseSettings): supabase_url: str`",
    "   - No client prefix needed — everything runs server-side.",
    "",
    "1. **DATABASE PATTERNS (FastAPI)**:",
    "   - SQLAlchemy: `engine = create_engine(os.environ['DATABASE_URL'])`",
    "   - Supabase: `from supabase import create_client; supabase = create_client(os.environ['SUPABASE_URL'], os.environ['SUPABASE_SERVICE_ROLE_KEY'])`",
    "   - Raw psycopg2/asyncpg for PostgreSQL.",
  ].join("\n"),

  routing: [
    "2. **FASTAPI ROUTING**: Routes use Python decorators.",
    "   - Main entry: `main.py` with `app = FastAPI()`",
    "   - Routes: `@app.get('/items')`, `@app.post('/items')`, `@app.get('/items/{item_id}')`",
    "   - Request body: use Pydantic models — `async def create(item: ItemCreate):`",
    "   - Response: return dict/Pydantic model (auto-serialized to JSON)",
    "   - Router groups: `from fastapi import APIRouter; router = APIRouter(prefix='/api')`",
    "   - Dependencies: `Depends()` for DI (auth, db sessions, etc.)",
    "",
    "**Structure:**",
    "   - `main.py` — FastAPI app + uvicorn start",
    "   - `routers/` — route modules by domain",
    "   - `models/` — Pydantic schemas + SQLAlchemy models",
    "   - `dependencies/` — shared deps (auth, db)",
    "",
    "2a. **CRITICAL: Client-side fetch URLs MUST be RELATIVE.**",
    "   FastAPI is API-only by default, but if the user serves an HTML/JS client",
    "   from this app (e.g. via `app.mount('/', StaticFiles(directory='static', html=True))`),",
    "   any browser `fetch()` runs inside Doable's preview iframe at",
    "   `/preview/<projectId>/`. Absolute paths starting with `/` hit Doable's",
    "   API host (404), NOT your FastAPI server.",
    "   Allowed patterns:",
    "   - Relative path from the served HTML: `fetch(\"./api/items\")`.",
    "   - Server-side: `request.url_for('route-name')` returns the full URL with the right host.",
    "   - For SPAs that need an API base, expose it via a small `<script>window.API_BASE = './api';</script>` injected by the server.",
    "   NEVER write `fetch(\"/api/items\")` in inline `<script>` blocks or static client JS — it WILL break in preview.",
  ].join("\n"),

  styling:
    "6. **NO STYLING**: This is a backend-only project. No CSS, HTML, or frontend code. If the user needs a frontend, suggest a separate project.",

  fileShape: [
    "7. **PYTHON PROJECT**: Use `.py` files. Dependencies in `requirements.txt`.",
    "",
    "8. **FASTAPI PATTERNS**:",
    "   ```python",
    "   from fastapi import FastAPI",
    "   from fastapi.middleware.cors import CORSMiddleware",
    "   ",
    "   app = FastAPI()",
    "   app.add_middleware(CORSMiddleware, allow_origins=['*'], allow_methods=['*'], allow_headers=['*'])",
    "   ",
    "   @app.get('/health')",
    "   async def health():",
    "       return {'status': 'ok'}",
    "   ```",
    "",
    "9. **TYPE HINTS**: Always use Python type hints. FastAPI uses them for validation and docs.",
    "",
    "10. **ASYNC**: Prefer `async def` route handlers. Use `asyncpg` or `databases` for async DB access.",
  ].join("\n"),
};
