import type { FrameworkPrompt } from "./index.js";

export const nuxtPrompt: FrameworkPrompt = {
  systemIntro:
    "The project is a Nuxt 3 + Vue 3 + TypeScript app with Tailwind CSS v4. Nuxt uses Nitro as its server engine and Vite for dev/HMR. It features file-based routing, server API routes, auto-imports, and hybrid rendering (SSR/SSG/SPA).",

  envConventions: [
    "0. **🔌 USE CONNECTED INTEGRATIONS**: If a `<connected-integrations>` block appears above, the user has already connected those services. You MUST reference the listed env vars and call the listed tools. NEVER ask the user to paste API keys, URLs, or tokens for any service in that block.",
    "",
    "0a. **ENV VAR PREFIX RULES (Nuxt)**:",
    "   - Server-only secrets: access via `process.env.X` in `server/` directory (API routes, middleware, plugins). Use `useRuntimeConfig()` for typed access — server keys go in `runtimeConfig` (NOT `runtimeConfig.public`).",
    "   - Browser-safe values: must be prefixed with `NUXT_PUBLIC_` and accessed via `useRuntimeConfig().public.x` in components.",
    "   - NEVER put a service-role key or password in `runtimeConfig.public` — it ships to the browser.",
    "   - In `nuxt.config.ts`: `runtimeConfig: { secretKey: '', public: { apiUrl: '' } }`",
    "",
    "0b. **🔌 SUPABASE NOT CONNECTED? PROVISION FIRST**: Call `provision_supabase` before writing Supabase code.",
    "",
    "1. **SUPABASE CLIENT PATTERNS (Nuxt)**:",
    "   - Server-side (`server/api/`): use `process.env.SUPABASE_SERVICE_ROLE_KEY`",
    "   - Client-side: use `useRuntimeConfig().public.supabaseUrl` + anon key",
    "   - Or install `@nuxtjs/supabase` module for auto-wired composables.",
  ].join("\n"),

  routing: [
    "2. **FILE-BASED ROUTING**: Nuxt uses the `pages/` directory.",
    "   - `pages/index.vue` → `/`",
    "   - `pages/about.vue` → `/about`",
    "   - `pages/blog/[slug].vue` → `/blog/:slug`",
    "   - `layouts/default.vue` → root layout",
    "   - Server routes: `server/api/items.ts` exporting `defineEventHandler()`",
    "   - Middleware: `middleware/auth.ts` for route guards",
    "   - Use `<NuxtLink to=\"/path\">` for navigation (NOT `<a href>` or vue-router directly).",
    "   - Use `navigateTo('/path')` for programmatic navigation.",
    "   - Do NOT install vue-router manually — Nuxt auto-configures it.",
    "",
    "**Server API routes**: `server/api/items.get.ts` for GET, `server/api/items.post.ts` for POST, or export from single file.",
    "",
    "**CRITICAL: Client-side fetch URLs MUST be RELATIVE**",
    "",
    "The Doable preview hosts your app inside an iframe at `/preview/<projectId>/`. An absolute fetch path like `fetch(\"/api/items\")` or `$fetch(\"/api/items\")` resolves to the iframe's ORIGIN root (Doable's API) — NOT your Nitro server route. Your fetch will hit Doable's API and 404.",
    "",
    "ALWAYS use one of:",
    "1. Relative paths: `fetch(\"./api/items\")` or `$fetch(\"./api/items\")` (resolves to `/preview/<id>/api/items` and is forwarded to your Nuxt dev server).",
    "2. `useRequestURL()` composable for SSR-safe origin discovery: `` const url = useRequestURL(); const data = await $fetch(`${url.origin}${url.pathname.replace(/\\/$/, \"\")}/api/items`) ``",
    "3. Explicit baseURL via runtime config: in `nuxt.config.ts` set `runtimeConfig: { public: { baseURL: '' } }`, then call `` $fetch(`${useRuntimeConfig().public.baseURL}/api/items`) ``.",
    "",
    "NEVER write `fetch(\"/api/items\")` or `$fetch(\"/api/items\")` with a leading slash from a client component, `<script setup>` running in the browser, or a `useFetch`/`useAsyncData` call that hydrates on the client. Server-side code (`server/api/*` handlers, server middleware, server-only `useAsyncData` callbacks gated by `import.meta.server`) is fine — it executes inside the Nitro server, not the browser.",
    "",
    "If you find yourself wanting `$fetch(\"/api/...\")` for simplicity, switch to a server-only data load (e.g. `useAsyncData` with `server: true` and a handler that runs on Nitro) so the call originates from your server, not the iframe.",
  ].join("\n"),

  styling: [
    "6. **TAILWIND CSS v4 (Nuxt)** — Via `@tailwindcss/postcss`:",
    "   - `assets/css/main.css` must start with `@import \"tailwindcss\";`",
    "   - Add to `nuxt.config.ts`: `css: ['~/assets/css/main.css']`",
    "   - NEVER use v3 directives or `@apply`. NEVER create tailwind.config files.",
    "   - Custom theme: `@theme` directive in the CSS file.",
  ].join("\n"),

  fileShape: [
    "7. **VUE 3 COMPOSITION API**: Always use `<script setup lang=\"ts\">` (NOT Options API).",
    "   - Reactive state: `const count = ref(0)` or `const state = reactive({...})`",
    "   - Computed: `const double = computed(() => count.value * 2)`",
    "   - Lifecycle: `onMounted(() => {...})`",
    "",
    "8. **AUTO-IMPORTS**: Nuxt auto-imports Vue APIs (`ref`, `computed`, `watch`), composables from `composables/`, and components from `components/`. Do NOT manually import these unless there's an ambiguity.",
    "",
    "9. **FILE STRUCTURE**:",
    "   - `pages/` — route pages (auto-routed)",
    "   - `components/` — auto-imported components",
    "   - `composables/` — auto-imported composables (use* naming)",
    "   - `server/api/` — server API endpoints",
    "   - `server/middleware/` — server middleware",
    "   - `layouts/` — page layouts",
    "   - `plugins/` — Nuxt plugins",
  ].join("\n"),
};
