import type { FrameworkPrompt } from "./index.js";

export const sveltekitPrompt: FrameworkPrompt = {
  systemIntro:
    "The project is a SvelteKit + Svelte 5 + TypeScript app with Tailwind CSS v4 (via @tailwindcss/vite). SvelteKit uses Vite under the hood for dev/HMR. It features file-based routing, server-side rendering, and API endpoints out of the box.",

  envConventions: [
    "0. **🔌 USE CONNECTED INTEGRATIONS**: If a `<connected-integrations>` block appears above, the user has already connected those services. You MUST reference the listed env vars and call the listed tools. NEVER ask the user to paste API keys, URLs, or tokens for any service in that block. If you need a service NOT in the block, call `request_integration` instead of asking for keys.",
    "",
    "0a. **ENV VAR PREFIX RULES (SvelteKit)**:",
    "   - Server-only secrets: access via `$env/static/private` or `$env/dynamic/private` in server files (+page.server.ts, +server.ts, hooks.server.ts). NEVER import private env in client code.",
    "   - Browser-safe values: must be prefixed with `PUBLIC_` and imported from `$env/static/public` or `$env/dynamic/public`.",
    "   - NEVER put a service-role key, secret key, or password in a `PUBLIC_*` var.",
    "   - Use `import { SUPABASE_SERVICE_ROLE_KEY } from '$env/static/private'` for server secrets.",
    "   - Use `import { PUBLIC_SUPABASE_URL } from '$env/static/public'` for browser-safe values.",
    "",
    "0b. **🔌 SUPABASE NOT CONNECTED? PROVISION FIRST**: If the user asks to add Supabase / a database but there is NO `supabase` entry in the `<connected-integrations>` block, you MUST call the `provision_supabase` tool BEFORE writing any code.",
    "",
    "1. **SUPABASE CLIENT PATTERNS (SvelteKit)**:",
    "   - Server-side (+page.server.ts, +server.ts): import from `$env/static/private`",
    "     ```ts",
    "     import { SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY } from '$env/static/private';",
    "     import { createClient } from '@supabase/supabase-js';",
    "     const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);",
    "     ```",
    "   - Client-side: import from `$env/static/public`",
    "     ```ts",
    "     import { PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY } from '$env/static/public';",
    "     const supabase = PUBLIC_SUPABASE_URL ? createClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY) : null;",
    "     ```",
  ].join("\n"),

  routing: [
    "2. **FILE-BASED ROUTING**: SvelteKit uses the `src/routes/` directory for routing.",
    "   - `src/routes/+page.svelte` → `/`",
    "   - `src/routes/about/+page.svelte` → `/about`",
    "   - `src/routes/blog/[slug]/+page.svelte` → `/blog/:slug`",
    "   - `src/routes/+layout.svelte` → root layout wrapping all pages",
    "   - Server routes: `src/routes/api/items/+server.ts` exporting `GET`, `POST`, etc.",
    "   - Load functions: `+page.server.ts` (server-only) or `+page.ts` (universal) for data loading.",
    "   - Form actions: `+page.server.ts` `export const actions = { default: async ({ request }) => {...} }`",
    "   - For navigation use `<a href=\"/path\">` or `goto('/path')` from `$app/navigation`.",
    "   - Do NOT install react-router-dom or any other routing library.",
    "",
    "**CRITICAL: Client-side fetch URLs MUST be RELATIVE**",
    "",
    "The Doable preview hosts your SvelteKit app inside an iframe at `/preview/<projectId>/`. An absolute fetch path like `fetch(\"/api/items\")` resolves to the iframe's ORIGIN root (Doable's API) — NOT your SvelteKit `+server.ts` route. Your fetch will hit Doable's API and 404.",
    "",
    "ALWAYS use one of:",
    "1. Relative paths: `fetch(\"./api/items\")` (resolves to `/preview/<id>/api/items` and is forwarded to your SvelteKit dev server). From a nested route like `/blog/[slug]`, use the correct relative depth (e.g. `fetch(\"../api/items\")`) or prefer option 3.",
    "2. Inside `+page.server.ts`, `+layout.server.ts`, or `+page.ts` `load` functions: use the SvelteKit-supplied `event.fetch` (a.k.a. the `fetch` argument). It is base-path aware and credentials-forwarding — `export async function load({ fetch }) { const r = await fetch('/api/items'); }` works correctly because SvelteKit rewrites the URL against the app's own origin and base path.",
    "3. The `base` constant from `$app/paths` for prefixing absolute paths in client code: `` import { base } from '$app/paths'; fetch(`${base}/api/items`) ``. SvelteKit injects the iframe's base path into `base` at runtime, so the request lands on your route, not Doable's API.",
    "",
    "NEVER write `fetch(\"/api/items\")` with a leading slash from a `<script>` block in a `.svelte` component, an `onMount`, an event handler, or any browser-side code. The leading slash escapes `/preview/<id>/` and hits Doable's API root.",
    "",
    "If you find yourself wanting `fetch(\"/api/...\")` for simplicity, move the data load into a `+page.server.ts` / `+layout.server.ts` `load` function and use the provided `event.fetch` — it runs on the SvelteKit server, sidesteps the iframe origin issue entirely, and lets you use absolute paths safely.",
  ].join("\n"),

  styling: [
    "6. **TAILWIND CSS v4 (SvelteKit)** — Wired through `@tailwindcss/vite` plugin:",
    "   - `src/app.css` must start with `@import \"tailwindcss\";` as the FIRST line. Import it from `+layout.svelte`.",
    "   - NEVER use `@tailwind base; @tailwind components; @tailwind utilities;` (v3 syntax).",
    "   - NEVER use `@apply` in CSS — removed in v4. Use utility classes directly.",
    "   - NEVER create a `tailwind.config.ts` / `tailwind.config.js` — v4 auto-detects.",
    "   - Custom theme: use `@theme` directive in `src/app.css`.",
  ].join("\n"),

  fileShape: [
    "7. **SVELTE 5 RUNES**: Use Svelte 5 runes syntax (NOT Svelte 4 stores):",
    "   - `$state()` for reactive state (replaces `let x = ...` reactive declarations)",
    "   - `$derived()` for computed values (replaces `$:` reactive statements)",
    "   - `$effect()` for side effects (replaces `onMount` + reactive statements)",
    "   - `$props()` for component props (replaces `export let`)",
    "   - `$bindable()` for two-way binding props",
    "",
    "8. **FILE NAMING**: Use `.svelte` for components, `.ts` for pure TypeScript. SvelteKit special files: `+page.svelte`, `+layout.svelte`, `+page.server.ts`, `+server.ts`, `+error.svelte`.",
    "",
    "9. **COMPONENT STRUCTURE**: Svelte files have `<script>`, optional `<style>`, and template markup (NOT JSX). Example:",
    "   ```svelte",
    "   <script lang=\"ts\">",
    "     let count = $state(0);",
    "   </script>",
    "   <button onclick={() => count++}>{count}</button>",
    "   ```",
  ].join("\n"),
};
