import type { FrameworkPrompt } from "./index.js";

/**
 * Vite + React framework prompt. Content is extracted VERBATIM from the
 * existing services/api/src/routes/chat/system-prompts.ts agent prompt
 * (lines 85, 253-264, 282, 306-319 plus the file-shape rules 7/10/11) so
 * that switching system-prompts.ts to renderFrameworkPrompt("vite-react")
 * preserves byte-identical AI behavior for the default scaffold.
 */
export const viteReactPrompt: FrameworkPrompt = {
  systemIntro:
    "The project is a Vite + React 19 + TypeScript app with Tailwind CSS v4 (using the @tailwindcss/vite plugin). Files are hot-reloaded via Vite.",

  envConventions: [
    "0. **🔌 USE CONNECTED INTEGRATIONS**: If a `<connected-integrations>` block appears above, the user has already connected those services. You MUST reference the listed env vars (via `import.meta.env.VITE_*` for client vars, `process.env.*` for server vars) and call the listed tools. NEVER ask the user to paste API keys, URLs, or tokens for any service in that block. If you need a service NOT in the block, call `request_integration` instead of asking for keys.",
    "",
    "0a. **🔌 INTEGRATION SDK (`@doable/sdk`)**: When the user wants to interact with external services (Slack, Stripe, Gmail, GitHub, etc.) from the generated app at runtime, use the `@doable/sdk` package. This SDK calls a secure server-side proxy — credentials never reach the browser.",
    "   ```ts",
    "   import { createDoableClient } from \"@doable/sdk\";",
    "   const doable = createDoableClient();",
    "   const result = await doable.integrations.run(\"slack\", \"send_channel_message\", { channel: \"#general\", text: \"Hello!\" });",
    "   if (result.success) { console.log(result.data); }",
    "   ```",
    "   For React components, use the hooks:",
    "   ```ts",
    "   import { useIntegration, useIntegrationQuery } from \"@doable/sdk/react\";",
    "   // Mutations:",
    "   const slack = useIntegration(\"slack\", \"send_channel_message\");",
    "   await slack.run({ channel: \"#general\", text: \"Hello\" });",
    "   // Queries (data fetching):",
    "   const { data, loading } = useIntegrationQuery(\"slack\", \"list_channels\", {});",
    "   ```",
    "   RULES:",
    "   - NEVER use fetch() to call external APIs directly (Slack API, Stripe API, etc.) — ALWAYS use the SDK",
    "   - NEVER hardcode API keys or tokens in the code",
    "   - The only exception is Supabase: use the direct Supabase client SDK (its keys are browser-safe)",
    "   - `@doable/sdk` is pre-installed in all projects — just import it, do NOT add it to package.json or run install_package for it",
    "",
    "0b. **🔌 MCP TOOLS IN GENERATED APPS**: When the generated app needs to call MCP server tools at runtime (e.g. fetching data from a connected MCP server like HPCA, Supabase MCP, or any custom MCP), use `@doable/sdk`'s MCP support:",
    "   ```ts",
    "   import { createDoableClient } from \"@doable/sdk\";",
    "   const doable = createDoableClient();",
    "   const result = await doable.mcp.call(\"mcp_connector_name_tool_name\", { param1: \"value\" });",
    "   if (result.success) { console.log(result.data); }",
    "   ```",
    "   To discover available MCP tools: `const tools = await doable.mcp.list();`",
    "   ▸ DASHBOARDS / WIDGETS (show specific data): call `doable.mcp.call(...)` directly inside a `useEffect` and render `result.data`. No AI loop needed.",
    "   ▸ AI CHATBOT / ASSISTANT over MCP (user asks free-form questions; the assistant decides which tool to call): DO NOT write your own tool-calling loop or parse tool calls yourself. Use the built-in agent helper `runMcpAgent` from `@doable/ai` — it discovers tools, runs the model↔tool ReAct loop, executes the right MCP tool, and returns an answer composed from REAL tool results:",
    "   ```ts",
    "   import { runMcpAgent } from \"@doable/ai\";",
    "   import { createDoableClient } from \"@doable/sdk\";",
    "   const doable = createDoableClient();",
    "   // in your chat send handler (userText = the user's message):",
    "   const { answer, toolsUsed } = await runMcpAgent({ mcp: doable.mcp, prompt: userText });",
    "   // render `answer` as markdown. Optional: { system, history, onToolCall, onToolResult } for app context + a 'calling…' indicator.",
    "   ```",
    "   RULES:",
    "   - Tool names use the AI-prefixed format: `mcp_{connectorName}_{toolName}` (all lowercase, non-alphanumeric → underscore)",
    "   - For conversational / assistant / chat UIs over MCP, ALWAYS use `runMcpAgent` from `@doable/ai`. NEVER hand-roll tool-call parsing — no greedy `/\\{[\\s\\S]*\\}/` regex, no single-shot `JSON.parse(reply.match(...))`. That breaks the instant the model emits more than one tool call and makes the assistant print raw JSON or hallucinate fake data instead of calling the tool.",
    "   - The assistant must answer from REAL tool results only. Never fabricate counts, rows, or records. `runMcpAgent` enforces this; if you build a custom flow you must feed the tool result back to the model before it answers.",
    "   - NEVER implement a custom postMessage bridge or raw fetch to MCP endpoints",
    "   - NEVER hardcode MCP server URLs or credentials in the app",
    "   - Auth is handled automatically (same as integrations)",
    "",
    "0c. **🔌 SUPABASE NOT CONNECTED? PROVISION FIRST**: If the user asks to add Supabase / a database but there is NO `supabase` entry in the `<connected-integrations>` block above (or the block is absent), you MUST call the `provision_supabase` tool BEFORE writing any code. Do NOT assume Supabase is connected — check the block. Do NOT ask the user for credentials. The provision tool opens a dialog for the user to connect their Supabase project, then injects the env vars automatically. Only after provisioning should you write Supabase client code.",
    "",
    "0d. **🗄️ PERSIST DATA IN THE INBUILT DATABASE — NEVER localStorage**: If a `## Per-app database` block appears above, this project has a built-in PGlite database. Whenever the user wants to store, save, persist, or load data (tasks, leads, posts, notes, any records), you MUST use it:",
    "   - ⛔ **SCHEMA FIRST — HARD GATE**: Before you write or edit ANY app code that runs `db.query` against a table, you MUST have created that table THIS SESSION with the `data.migrate` tool. The `/__doable/data/query` endpoint the app uses CANNOT run `CREATE TABLE` (DDL is rejected there), and `db.exec` throws in app code — so a table the app references but you never migrated simply DOES NOT EXIST, every query fails silently, and the app shows empty data forever. This is the #1 cause of \"my app won't save anything\". The correct order, every time, is: (1) call `data.migrate` to create the table(s) → (2) optionally call `data.schema` to verify → (3) THEN write the app code that queries them. Do NOT emit the app's `SELECT/INSERT` code and assume the table exists.",
    "   - At BUILD time: create the schema with the `data.migrate` tool (one call per table, e.g. migration_id `0001_init_tasks`). Use `CREATE TABLE IF NOT EXISTS` so re-running is safe. Then inspect with `data.schema` before writing app code.",
    "   - 🔑 **RLS OWNER COLUMN MUST SELF-STAMP — or your INSERTs are silently rejected.** Every table gets an RLS owner policy keyed on `created_by`, so the `created_by` column MUST carry this EXACT default so an INSERT that omits it still satisfies the policy's `WITH CHECK` (otherwise the write fails with RLS_VIOLATION and nothing persists — the #2 cause of \"my app won't save anything\"). Copy this template verbatim, every table:",
    "     ```sql",
    "     CREATE TABLE IF NOT EXISTS <name> (",
    "       id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),",
    "       created_by  uuid NOT NULL DEFAULT (nullif(current_setting('app.user_id', true), ''))::uuid,",
    "       created_at  timestamptz NOT NULL DEFAULT now()",
    "       -- your columns",
    "     );",
    "     ALTER TABLE <name> ENABLE ROW LEVEL SECURITY;",
    "     CREATE POLICY <name>_owner ON <name>",
    "       USING (created_by::text = current_setting('app.user_id', true))",
    "       WITH CHECK (created_by::text = current_setting('app.user_id', true));",
    "     ```",
    "   - 🚫 **IN APP CODE, NEVER set `created_by` in an INSERT and NEVER filter SELECTs by it.** Just INSERT your business columns (`INSERT INTO tasks (title) VALUES ($1)`) — the column DEFAULT stamps the owner from the signed-in user automatically, and RLS auto-scopes every read/write. Manually passing a `created_by` value will mismatch the session identity and the row is rejected (RLS_VIOLATION) or invisible.",
    "   - At RUNTIME: `import { db } from \"@doable/data\"` and call `db.query(sql, params)`. The package is PRE-LINKED into every project — it is NOT in package.json and that is correct; import it directly, NEVER install_package it or add it to package.json. The identity token is injected automatically (`globalThis.__DOABLE_DATA_TOKEN`).",
    "   - `db.query` returns `{ ok, rows, rowCount, error }` and does NOT throw — check `r.ok` before reading `r.rows`. `db.exec` is server-only; never call it from app code.",
    "   ```ts",
    "   import { db } from \"@doable/data\";",
    "   const r = await db.query<{ id: string; title: string }>(\"SELECT id, title FROM tasks ORDER BY created_at DESC LIMIT $1\", [50]);",
    "   const tasks = r.ok ? r.rows : [];",
    "   ```",
    "   🚫 FORBIDDEN as the data store: localStorage, sessionStorage, IndexedDB, in-memory arrays, AND importing `@electric-sql/pglite` or calling `new PGlite()` in app code (that is a throwaway in-browser DB that loses data on reload — NOT the inbuilt DB). They are acceptable ONLY for trivial ephemeral UI state (theme toggle, sidebar collapsed, an in-progress draft) — NEVER for persisting real user records. `@doable/data` being absent from package.json is NOT a reason to fall back — it is PRE-LINKED; import it directly.",
    "",
    "1. **🚨 GUARD SUPABASE CLIENT 🚨**: When using `@supabase/supabase-js`, ALWAYS guard against missing env vars. The Supabase client THROWS if the URL is undefined — crashing the entire app with a white screen. Write it like this:",
    "   ```ts",
    "   const url = import.meta.env.VITE_SUPABASE_URL ?? \"\";",
    "   const key = import.meta.env.VITE_SUPABASE_ANON_KEY ?? \"\";",
    "   export const supabase = url ? createClient(url, key, { auth: { persistSession: false, detectSessionInUrl: false } }) : null;",
    "   ```",
    "   Then in components, check `if (!supabase)` and show a \"Connecting to database...\" placeholder instead of crashing.",
    "   NOTE: `persistSession: false` is REQUIRED because the preview runs in a sandboxed iframe where `navigator.locks` is blocked.",
  ].join("\n"),

  routing: [
    "2. **🚨 USE HashRouter NOT BrowserRouter 🚨**: When using react-router-dom, ALWAYS use `HashRouter` (not `BrowserRouter`). The live preview runs at a sub-path (`/preview/{projectId}/`) so BrowserRouter's path-based routing doesn't match. HashRouter uses `#/` which works at any base URL. Import: `import { HashRouter, Routes, Route } from \"react-router-dom\";`",
    "",
    "   **🚨 ONLY ONE ROUTER — IN App.tsx ONLY 🚨**: You MUST place the `<HashRouter>` wrapper ONLY inside `src/App.tsx`. NEVER add a Router in `src/main.tsx` — that file is fixed infrastructure (ErrorBoundary + StrictMode + `<App />`). If you put `<HashRouter>` in BOTH main.tsx and App.tsx you get \"You cannot render a <Router> inside another <Router>\" which crashes the preview to a white screen. Pattern:",
    "   ```tsx",
    "   // src/App.tsx — Router goes HERE",
    "   export default function App() {",
    "     return (",
    "       <HashRouter>",
    "         <Routes>",
    "           <Route path=\"/\" element={<Home />} />",
    "         </Routes>",
    "       </HashRouter>",
    "     );",
    "   }",
    "   ```",
    "   NEVER do this in main.tsx:",
    "   ```tsx",
    "   // ❌ WRONG — main.tsx must NOT have a Router",
    "   <HashRouter><App /></HashRouter>",
    "   ```",
  ].join("\n"),

  styling: [
    "6. **TAILWIND CSS v4** — This project uses Tailwind v4 which is very different from v3:",
    "   - ALWAYS start index.css with: `@import \"tailwindcss\";` as the FIRST line",
    "   - NEVER use `@tailwind base; @tailwind components; @tailwind utilities;` (that is v3 syntax, it will break)",
    "   - NEVER use `@apply` in CSS — it is removed in Tailwind v4 by default. Use utility classes directly in JSX instead.",
    "   - NEVER create a tailwind.config.ts or tailwind.config.js — it's not needed. Tailwind v4 auto-detects utility classes.",
    "   - For custom theme values (colors, fonts, spacing), use the `@theme` directive in CSS:",
    "     ```css",
    "     @import \"tailwindcss\";",
    "     @theme {",
    "       --color-brand: #3b82f6;",
    "       --font-heading: \"Inter\", sans-serif;",
    "     }",
    "     ```",
    "   - Then use them as classes: `className=\"text-brand font-heading\"`",
    "   - **🚨 NEVER STRIP THE SHADCN @THEME COLOR BRIDGES 🚨** — the scaffold's `index.css` defines `--background`, `--foreground`, `--muted`, `--card`, `--border`, `--primary`, etc. as raw HSL triplets under `:root`/`.dark`, AND aliases them inside `@theme` as `--color-background: hsl(var(--background))`, `--color-foreground: hsl(var(--foreground))`, etc.",
    "   - Tailwind v4 ONLY emits a utility (`.text-foreground`, `.bg-background`, `.text-card-foreground`, etc.) when its underlying `--color-*` token exists inside `@theme`. If you remove or shrink the `@theme` block, those utilities silently disappear and every element using them renders with no color rule → invisible text.",
    "   - When you EDIT `index.css`, you may ADD new tokens (e.g. `--color-accent: hsl(...)`) but you MUST PRESERVE every `--color-*` line that already exists. If you rewrite the file from scratch, copy the existing `@theme` block VERBATIM — do not collapse it to just brand/font/radius tokens.",
  ].join("\n"),

  fileShape: [
    "7. **DEFAULT EXPORT**: src/App.tsx must use `export default` since src/main.tsx imports it as a default import.",
    "",
    "10. **FILE EXTENSIONS**: Always use `.tsx` for files containing JSX/TSX markup. Use `.ts` for pure TypeScript files with no JSX. Never put JSX in a `.ts` file.",
    "",
    "11. **IMPORT TYPES**: Do not use `import type { X }` for values that are used at runtime (e.g., as a component, in a function call, or as a value). `import type` strips the import at compile time, causing runtime errors. Only use `import type` for values used exclusively in type annotations.",
    "",
    "13. **FILE TOOLS — USE ONLY `create_file` / `edit_file` WITH RELATIVE PATHS**: To create or modify ANY file you MUST use Doable's `create_file` and `edit_file` tools. NEVER use the built-in editor tools `str_replace_editor`, `str_replace`, `edit`, `multi_edit`, `view`, `write`, or `create` — they expect absolute `/app/...` paths and a read-before-edit protocol that DO NOT apply here and will only waste your turns with errors like \"File already exists\", \"File has not been read yet\", or \"Path must be absolute\". If you EVER see one of those errors, STOP using that tool and switch to `create_file`/`edit_file` with a project-relative path. `create_file` OVERWRITES the file if it already exists, so for a full-file change just call `create_file` directly — you do NOT need to read, view, or delete the file first. The fields are EXACTLY:",
    "   - `path` (string, RELATIVE to the project root, e.g. `\"index.css\"`, `\"src/App.tsx\"`)",
    "   - `content` (string, the full file content)",
    "   Do NOT use `file_text` — that field does not exist on these tools. Do NOT pass `command: \"create\"` — these tools don't take a command field. Do NOT prefix paths with `/app/`, `/`, or `./` — paths are always relative to the project root. The platform normalizes paths automatically, so just pass the project-relative path and the `content` field.",
    "   Example: `create_file({ path: \"src/App.tsx\", content: \"export default function App() { return <div>Hi</div>; }\" })`",
  ].join("\n"),

  pwa: [
    "12. **PWA (Progressive Web App)**: When the user asks to make the app installable, work offline, or become a PWA:",
    "   - Install `vite-plugin-pwa` (devDependency) and `idb-keyval` (dependency)",
    "   - **CRITICAL**: Add `import { VitePWA } from \"vite-plugin-pwa\"` and `VitePWA({...})` to the plugins array in vite.config.ts — WITHOUT this, NO service worker, manifest, or registerSW.js will be generated",
    "   - Configure manifest INSIDE VitePWA() options (do NOT create a separate manifest.json)",
    "   - Use `scope: \"./\"` and `start_url: \"./\"` (relative paths — required for sub-path deployment)",
    "   - NEVER create sw.js manually — vite-plugin-pwa auto-generates it via Workbox",
    "   - NEVER call navigator.serviceWorker.register() — the plugin handles it",
    "   - Add to index.html: meta theme-color, apple-mobile-web-app-capable, apple-touch-icon, viewport-fit=cover",
    "   - Provide icons: 192×192 + 512×512 PNG (include one with purpose: \"maskable\")",
    "   - Add BeforeInstallPromptEvent type declaration in vite-env.d.ts",
    "   - **IMPORTANT**: Wrap ALL idb-keyval/IndexedDB calls in try/catch — the preview iframe sandbox blocks IndexedDB; fall back to in-memory or localStorage on SecurityError",
    "   - Caching: CacheFirst for static assets/fonts, NetworkFirst for API calls",
    "   - Add env(safe-area-inset-*) padding on body for iPhone notch",
  ].join("\n"),
};
