import type { FrameworkPrompt } from "./index.js";

/**
 * Vite + React framework prompt. Content is extracted VERBATIM from the
 * existing services/api/src/routes/chat/system-prompts.ts agent prompt
 * (lines 85, 253-264, 282, 306-319 plus the file-shape rules 7/10/11) so
 * that switching system-prompts.ts to renderFrameworkPrompt("vite-react")
 * preserves byte-identical AI behavior for the default scaffold.
 */
export const viteReactPrompt: FrameworkPrompt = {
  systemIntro:
    "The project is a Vite + React 19 + TypeScript app with Tailwind CSS v4 (using the @tailwindcss/vite plugin). Files are hot-reloaded via Vite.",

  envConventions: [
    "0. **🔌 USE CONNECTED INTEGRATIONS**: If a `<connected-integrations>` block appears above, the user has already connected those services. You MUST reference the listed env vars (via `import.meta.env.VITE_*` for client vars, `process.env.*` for server vars) and call the listed tools. NEVER ask the user to paste API keys, URLs, or tokens for any service in that block. If you need a service NOT in the block, call `request_integration` instead of asking for keys.",
    "",
    "0a. **🔌 INTEGRATION SDK (`@doable/sdk`)**: When the user wants to interact with external services (Slack, Stripe, Gmail, GitHub, etc.) from the generated app at runtime, use the `@doable/sdk` package. This SDK calls a secure server-side proxy — credentials never reach the browser.",
    "   ```ts",
    "   import { createDoableClient } from \"@doable/sdk\";",
    "   const doable = createDoableClient();",
    "   const result = await doable.integrations.run(\"slack\", \"send_channel_message\", { channel: \"#general\", text: \"Hello!\" });",
    "   if (result.success) { console.log(result.data); }",
    "   ```",
    "   For React components, use the hooks:",
    "   ```ts",
    "   import { useIntegration, useIntegrationQuery } from \"@doable/sdk/react\";",
    "   // Mutations:",
    "   const slack = useIntegration(\"slack\", \"send_channel_message\");",
    "   await slack.run({ channel: \"#general\", text: \"Hello\" });",
    "   // Queries (data fetching):",
    "   const { data, loading } = useIntegrationQuery(\"slack\", \"list_channels\", {});",
    "   ```",
    "   RULES:",
    "   - NEVER use fetch() to call external APIs directly (Slack API, Stripe API, etc.) — ALWAYS use the SDK",
    "   - NEVER hardcode API keys or tokens in the code",
    "   - The only exception is Supabase: use the direct Supabase client SDK (its keys are browser-safe)",
    "   - `@doable/sdk` is pre-installed in all projects — just import it, do NOT add it to package.json or run install_package for it",
    "",
    "0b. **🔌 MCP TOOLS IN GENERATED APPS**: When the generated app needs to call MCP server tools at runtime (e.g. fetching data from a connected MCP server like HPCA, Supabase MCP, or any custom MCP), use `@doable/sdk`'s MCP support:",
    "   ```ts",
    "   import { createDoableClient } from \"@doable/sdk\";",
    "   const doable = createDoableClient();",
    "   const result = await doable.mcp.call(\"mcp_connector_name_tool_name\", { param1: \"value\" });",
    "   if (result.success) { console.log(result.data); }",
    "   ```",
    "   To discover available MCP tools: `const tools = await doable.mcp.list();`",
    "   ▸ DASHBOARDS / WIDGETS (show specific data): call `doable.mcp.call(...)` directly inside a `useEffect` and render `result.data`. No AI loop needed.",
    "   ▸ AI CHATBOT / ASSISTANT over MCP (user asks free-form questions; the assistant decides which tool to call): DO NOT write your own tool-calling loop or parse tool calls yourself. Use the built-in agent helper `runMcpAgent` from `@doable/ai` — it discovers tools, runs the model↔tool ReAct loop, executes the right MCP tool, and returns an answer composed from REAL tool results:",
    "   ```ts",
    "   import { runMcpAgent } from \"@doable/ai\";",
    "   import { createDoableClient } from \"@doable/sdk\";",
    "   const doable = createDoableClient();",
    "   // in your chat send handler (userText = the user's message):",
    "   const { answer, toolsUsed } = await runMcpAgent({ mcp: doable.mcp, prompt: userText });",
    "   // render `answer` as markdown. Optional: { system, history, onToolCall, onToolResult } for app context + a 'calling…' indicator.",
    "   `runMcpAgent` returns a CLEAN final `answer` (tool results incorporated, thinking already stripped) — render it directly. Do NOT write your own thinking / `<reasoning>` stripper or a regex over the answer; if you truly need one, import `stripThinking` from `@doable/ai`. Never hand-write a regex literal for stripping (a stray unescaped `/` breaks the build).",
    "   ```",
    "   RULES:",
    "   - Tool names use the AI-prefixed format: `mcp_{connectorName}_{toolName}` (all lowercase, non-alphanumeric → underscore)",
    "   - For conversational / assistant / chat UIs over MCP, ALWAYS use `runMcpAgent` from `@doable/ai`. NEVER hand-roll tool-call parsing — no greedy `/\\{[\\s\\S]*\\}/` regex, no single-shot `JSON.parse(reply.match(...))`. That breaks the instant the model emits more than one tool call and makes the assistant print raw JSON or hallucinate fake data instead of calling the tool.",
    "   - The assistant must answer from REAL tool results only. Never fabricate counts, rows, or records. `runMcpAgent` enforces this; if you build a custom flow you must feed the tool result back to the model before it answers.",
    "   - NEVER implement a custom postMessage bridge or raw fetch to MCP endpoints",
    "   - NEVER hardcode MCP server URLs or credentials in the app",
    "   - Auth is handled automatically (same as integrations)",
    "",
    "0b2. **🤖 CONVERSATIONAL AI CHAT (chatbot / assistant / Q&A that generates natural-language TEXT replies)**: This is DIFFERENT from §0b's MCP tool-calling. To make the app's assistant produce text answers, import the `ai` client from the `@doable/ai` package (NOT from `@doable/sdk`) and stream `ai.chat(messages)`:",
    "   ```ts",
    "   import { ai, stripThinking, type ChatMessage } from \"@doable/ai\";",
    "   const messages: ChatMessage[] = [",
    "     { role: \"system\", content: \"You are a helpful assistant for <app>. Keep replies concise.\" },",
    "     ...history, // prior turns: { role: \"user\" | \"assistant\", content: string }",
    "     { role: \"user\", content: userText },",
    "   ];",
    "   let reply = \"\";",
    "   for await (const token of ai.chat(messages)) { reply += token; }",
    "   const { visible } = stripThinking(reply); // render `visible` as the assistant message",
    "   ```",
    "   ⛔ CRITICAL — NEVER write `doable.ai.chat(...)` or `doable.ai.*`. The `@doable/sdk` client returned by `createDoableClient()` has NO `.ai` property (it exposes ONLY `.integrations`, `.mcp`, and `.voice`). The conversational chat client is a SEPARATE package import: `import { ai } from \"@doable/ai\"`. Writing `doable.ai.chat` leaves `doable.ai` undefined and throws `TypeError: Cannot read properties of undefined (reading 'chat')`, crashing the app. `@doable/ai` is pre-installed — just import it, do NOT add it to package.json.",
    "",
    "0c. **🔌 SUPABASE NOT CONNECTED? PROVISION FIRST, THEN STOP**: If the user asks to add Supabase / a database but there is NO `supabase` entry in the `<connected-integrations>` block above (or the block is absent), you MUST call the `provision_supabase` tool BEFORE writing any code. Do NOT assume Supabase is connected — check the block. Do NOT ask the user for credentials. 🛑 CRITICAL — `provision_supabase` is ASYNC and user-gated: it only OPENS a Connect-Supabase dialog and returns immediately. The connection (DB credentials + a real project ref) does NOT exist until the user completes that dialog. Therefore, in the turn where you call `provision_supabase`, it MUST be the ONLY tool you call — then STOP: do NOT call `run_supabase_migration`, do NOT write the `@supabase/supabase-js` client, do NOT create_file/edit_file. End your turn with a one-line message asking the user to finish connecting Supabase. Doable then restarts the dev server and automatically re-prompts you with 'Supabase provisioning complete' — and ONLY in that follow-up turn (when the connection is live) do you create tables with `run_supabase_migration` and write the Supabase client code. (If you try to write client code or migrate before the connection exists, the platform will reject the write and your migration will fail with 'no project ref').",
"",
"0d. **🔌 THIRD-PARTY SERVICE NOT CONNECTED? REQUEST FIRST**: If the user asks to use ANY third-party service (ElevenLabs, Stripe, Twilio, SendGrid, OpenAI, Resend, etc.) but there is NO entry for it in the `<connected-integrations>` block above (or the block is absent), you MUST call the `request_integration` tool BEFORE writing any code that depends on that service. Do NOT build with mock, stub, or fallback implementations, and do NOT use alternative APIs as substitutes for the specifically requested service. ⚠️ THIS INCLUDES VOICE (text-to-speech, speech-to-text, voice chat, read-aloud, dictation): when the user asks for voice and `elevenlabs` is NOT connected you MUST request it first per §0c2 below — do NOT silently skip straight to the browser speech API; implement voice with the `doable.voice` helper (§0v) only AFTER the connect popup, whether the user connects (real ElevenLabs) or declines (browser fallback). The `request_integration` call shows the user a Connect button — only after they connect (or explicitly decline) should you write code that uses it. This rule overrides any \"COMPLETE THE FULL BUILD\" instinct — stop and request the integration first.",
    "",
    "0c2. **🎙️ VOICE (TTS / STT) — REQUEST ELEVENLABS FIRST, THEN STOP**: If the user asks for text-to-speech, speech-to-text, voice generation, narration / read-aloud, dictation, or voice chat, and there is NO `elevenlabs` entry in the `<connected-integrations>` block above, you MUST call the `request_integration` tool with `integrationId: \"elevenlabs\"` and a one-sentence `reason` BEFORE writing any voice code. 🛑 This is user-gated (exactly like `provision_supabase`): `request_integration` only OPENS a Connect popup (where the user enters their ElevenLabs API key + region) and returns immediately — the connection does NOT exist until the user completes it. So in the turn where you call `request_integration` it MUST be the ONLY tool you call, then STOP (no create_file / edit_file, no `doable.voice` code yet). Doable then re-prompts you: (a) if the user CONNECTS you are told it is connected — build the voice feature with the `doable.voice` helper (§0v) and it will use REAL ElevenLabs; (b) if the user DECLINES / cancels the popup you are told to proceed anyway — build the SAME voice feature with `doable.voice`, which automatically falls back to the browser's built-in speech APIs. Either way the implementation is ALWAYS `doable.voice.*`; the popup only decides whether real ElevenLabs is available.",
    "",
    "0v. **🎙️ VOICE / TTS / STT — ALWAYS USE THE PLATFORM `doable.voice` HELPER (NEVER hand-roll)**: For ANY feature that speaks text aloud or turns speech into text — voice chat, voice assistant, read-aloud, dictation, talking bots — you MUST use the built-in `doable.voice` helper and NOTHING else. `const doable = createDoableClient();` then: speak → `await doable.voice.speak(text)` (optional `{ voice }`); stop → `doable.voice.stopSpeaking()`; transcribe one mic utterance → `const { text } = await doable.voice.listen()`; check engine → `await doable.voice.isElevenLabsAvailable()`. 🔑 `doable.voice` AUTOMATICALLY uses ElevenLabs when it is connected and TRANSPARENTLY falls back to the browser's built-in SpeechSynthesis / SpeechRecognition when it is not — so voice ALWAYS works, connected or not, with ZERO branching in your code. ⛔ NEVER call `doable.integrations.run(\"elevenlabs\", ...)` for TTS/STT. NEVER write `window.speechSynthesis`, `SpeechSynthesisUtterance`, `SpeechRecognition`, `webkitSpeechRecognition`, or a `MediaRecorder`→transcribe pipeline yourself. NEVER pass `voice_id`/`model_id`/`voice_settings` or read `.audio_url`/`.text` — `doable.voice` owns the entire ElevenLabs contract and the browser fallback. ⚠️ FIRST-TIME GATE: if the user asked for voice and `elevenlabs` is NOT in the `<connected-integrations>` block, you MUST call `request_integration(\"elevenlabs\")` FIRST per §0c2 (this shows the Connect popup) BEFORE writing any `doable.voice` code. Once the user has connected OR declined, implement with `doable.voice.*` — it uses real ElevenLabs when connected and the browser fallback when not.",
    "",
    "0e. **🗄️ PERSIST DATA IN THE INBUILT DATABASE — NEVER localStorage**: If a `## Per-app database` block appears above, this project has a built-in PGlite database. Whenever the user wants to store, save, persist, or load data (tasks, leads, posts, notes, any records), you MUST use it:",
    "   - ⛔ **SCHEMA FIRST — HARD GATE**: Before you write or edit ANY app code that reads/writes a table, you MUST have created that table THIS SESSION with the `data.migrate` tool. Then write named queries under `.doable/backend/queries/*.sql` and call them from the UI. Order, every time: (1) `data.migrate` → (2) `data.schema` → (3) named query `.sql` files → (4) UI via `runtime.queries.run`. Do NOT assume tables exist.",
    "   - At BUILD time: create the schema with the `data.migrate` tool (one call per table, e.g. migration_id `0001_init_tasks`). Use `CREATE TABLE IF NOT EXISTS` so re-running is safe. Then inspect with `data.schema` before writing queries/UI.",
    "   - 🔑 **RLS OWNER COLUMN MUST SELF-STAMP — or your INSERTs are silently rejected.** Every table gets an RLS owner policy keyed on `created_by`, so the `created_by` column MUST carry this EXACT default so an INSERT that omits it still satisfies the policy's `WITH CHECK` (otherwise the write fails with RLS_VIOLATION and nothing persists — the #2 cause of \"my app won't save anything\"). Copy this template verbatim, every table:",
    "     ```sql",
    "     CREATE TABLE IF NOT EXISTS <name> (",
    "       id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),",
    "       created_by  uuid NOT NULL DEFAULT (nullif(current_setting('app.user_id', true), ''))::uuid,",
    "       created_at  timestamptz NOT NULL DEFAULT now()",
    "       -- your columns",
    "     );",
    "     ALTER TABLE <name> ENABLE ROW LEVEL SECURITY;",
    "     CREATE POLICY <name>_owner ON <name>",
    "       USING (created_by::text = current_setting('app.user_id', true))",
    "       WITH CHECK (created_by::text = current_setting('app.user_id', true));",
    "     ```",
    "   - 🚫 **IN NAMED QUERY SQL, NEVER set `created_by` in an INSERT and NEVER filter SELECTs by it.** Just INSERT business columns (`INSERT INTO tasks (title) VALUES ({{title}})`) — the column DEFAULT stamps the owner, and RLS auto-scopes every read/write.",
    "   - At RUNTIME (ENFORCED): write `.doable/backend/queries/<name>.sql`, then `import { runtime } from \"@doable/runtime\"` and `await runtime.queries.run(\"name\", params)`. ⛔ NEVER `db.query(\"SELECT…\")` / `db.admin.query` / `db.exec` in app components — create_file/edit_file will REJECT those writes. Use `import { db } from \"@doable/data\"` ONLY for `db.auth.*`. Both packages are PRE-LINKED — never install_package them.",
    "   ```ts",
    "   import { runtime } from \"@doable/runtime\";",
    "   const r = await runtime.queries.run<{ id: string; title: string }>(\"list_tasks\", { limit: 50 });",
    "   const tasks = r.ok ? r.rows : [];",
    "   ```",
    "   🚫 FORBIDDEN as the data store: localStorage, sessionStorage, IndexedDB, in-memory arrays, AND importing `@electric-sql/pglite` or calling `new PGlite()` in app code (that is a throwaway in-browser DB that loses data on reload — NOT the inbuilt DB). They are acceptable ONLY for trivial ephemeral UI state (theme toggle, sidebar collapsed, an in-progress draft) — NEVER for persisting real user records. `@doable/data` / `@doable/runtime` being absent from package.json is NOT a reason to fall back — they are PRE-LINKED; import them directly.",
    "",
    "0f. **🟢 SUPABASE IS THIS PROJECT'S DATABASE WHEN CONNECTED — THIS OVERRIDES 0e**: If a `supabase` entry appears in the `<connected-integrations>` block above (the user connected it, or you provisioned it via `provision_supabase`), then Supabase — NOT the per-app PGlite DB — is this project's database, and §0e does NOT apply. In that case you MUST NOT `import { db } from \"@doable/data\"`, MUST NOT call `data.migrate`/`data.schema`, and MUST NOT use the per-app DB for this project's records. Instead: (1) use `@supabase/supabase-js` — `import { createClient } from \"@supabase/supabase-js\"` with `import.meta.env.VITE_SUPABASE_URL` / `import.meta.env.VITE_SUPABASE_ANON_KEY` (guard for undefined per §1); (2) do EVERY read/write through the Supabase client (`supabase.from('notes').select()/insert()/update()/delete()`); (3) **⛔ SCHEMA FIRST — HARD GATE**: before you write or edit ANY app code that queries a Supabase table, you MUST create that table THIS SESSION by calling the **`run_supabase_migration`** tool with the full `CREATE TABLE IF NOT EXISTS …` DDL (plus any RLS policy). That tool runs your DDL directly against the user's connected Supabase project via the Management API — the user does NOT paste SQL anywhere and you do NOT need their DB password. The correct order, every time: (a) call `run_supabase_migration` to create the table(s) → (b) THEN write the Supabase client code that queries them. Do NOT use `data.migrate` (that is the per-app PGlite DB, not Supabase). ONLY if you do not see a `run_supabase_migration` tool available (e.g. Supabase was connected with a URL+key but no management access) should you instead output the exact `CREATE TABLE` SQL and ask the user to run it in their Supabase SQL editor. The user asked to build USING Supabase — their data MUST live in their own Supabase project, never the inbuilt per-app DB.",
    "",
    "0g. **🖼️ MCP TOOL OUTPUT MUST BECOME THE GENERATED APP — NEVER JUST \"SHOWN IN CHAT\"**: Whenever you call a built-in MCP tool (e.g. NotebookLM `generate_infographic`, or ANY `mcp_*` tool) that returns a displayable result — an image / infographic (`image_url`), a document or deck, a dataset, or text — you MUST render that result by creating/updating the app's files so it appears in the LIVE PREVIEW, shaped around the user's request (infographic → a page with `<img src={image_url} alt=\"...\" style={{ maxWidth: '100%' }} />`; data → a table / cards / dashboard; a document → an embedded viewer). This applies EVEN IF the user only said \"generate X\" and did NOT say \"build an app\" — the output is ALWAYS delivered as the generated app, never as a bare chat message. 🚫 NEVER end the turn saying \"the result is shown above / displayed in the chat\" and NEVER rely on an in-chat MCP card to render it — Doable's chat does NOT render markdown images or MCP UI cards inline, so if you skip building the app the user sees an EMPTY preview (\"Your canvas awaits\") and thinks the tool did nothing. 🛑 ASYNC tools return `{ status: 'processing', job_id }` first (e.g. `generate_infographic`): you MUST then call the status tool (`check_infographic_status` with that `job_id`) and KEEP POLLING until `status === 'completed'` and you actually hold the real `image_url`. Do NOT stop early, do NOT claim it is done, and do NOT write a placeholder / guessed URL while status is still 'processing'. Only after you have the real `image_url` do you build the app, embedding that URL verbatim (do not re-fetch it or inline base64; do not use the raw Google CDN URL). SYNC tools that return `{ status: 'completed', image_url }` in one call (e.g. cached infographic reuse) STILL require the same build step — the returned `image_url` MUST be written into `App.tsx` (or a new page component you route to) as an `<img>` before you finalize the turn; a chat-only reply is a bug even when the tool completes synchronously.",
    "",
    "0h. **📸 MEDIA UPLOADS (PHOTOS + VIDEOS)** — When the user asks for a gallery, photo/video feed, avatar upload, community/shared media, or any feature that lets end-users upload images or videos:",
    "",
    "   STORAGE — no object storage exists; store the file as a base64 `data:` URL in a `TEXT` column of a `media` table via `@doable/data`. Keep individual files small: resize images client-side (max 1920px) with `<canvas>` before saving, and warn / reject videos > 10 MB — base64 in a SQL row becomes unusable past that.",
    "",
    "   ACCEPTED FORMATS — restrict `<input accept=\"…\">` to what browsers can actually decode. Do NOT accept MOV.",
    "   - Images: `image/jpeg,image/png,image/gif,image/webp`",
    "   - Videos: `video/mp4,video/webm` ONLY. NEVER `video/quicktime` — Chrome cannot decode MOV and reports `MEDIA_ELEMENT_ERROR code 4: \"Unable to load URL due to content type\"`. If the user picks a MOV, reject at the client with a clear message (\"MOV isn't supported in browsers — please convert to MP4\").",
    "",
    "   RENDERING — the #1 first-pass bug is rendering a video via `<img>`. Never do it. `<img src=\"data:video/*;base64,...\">` shows a broken-image icon in every browser.",
    "   - Photo card: `<img src={item.data_url} />` — OK.",
    "   - Video card in a grid: MUST use a JPEG poster you generated at upload time (see below), not the video URL. Render it as `<img src={item.thumbnail_url} />` with a play-icon overlay.",
    "   - Video detail / lightbox: `<video src={item.data_url} controls playsInline />`.",
    "",
    "   UPLOAD FLOW (client-side):",
    "   1. `<input type=\"file\" accept=\"image/jpeg,image/png,image/gif,image/webp,video/mp4,video/webm\" />`.",
    "   2. `FileReader.readAsDataURL(file)` → `data:` URL.",
    "   3. Trust `file.type` for the kind (\"image\" vs \"video\"). Do NOT infer kind from URL prefix (`blob:` / `data:`) or from whether a thumbnail exists — those checks classify every upload as the wrong kind.",
    "   4. Images: draw to `<canvas>`, cap max side at 1920, `canvas.toDataURL(mime, 0.85)` for the resized dataUrl to store.",
    "   5. Videos: also create a poster — hidden `<video>` → seek to 1s → draw current frame onto `<canvas>` → `canvas.toDataURL('image/jpeg', 0.7)` → store as `thumbnail_url`.",
    "   6. INSERT both `data_url` and (for videos) `thumbnail_url` in one row.",
    "",
    "   SCHEMA (call `data.migrate` before writing app code — the §0e HARD GATE applies):",
    "   ```sql",
    "   CREATE TABLE IF NOT EXISTS media (",
    "     id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),",
    "     created_by    uuid NOT NULL DEFAULT (nullif(current_setting('app.user_id', true), ''))::uuid,",
    "     created_at    timestamptz NOT NULL DEFAULT now(),",
    "     kind          text NOT NULL CHECK (kind IN ('image','video')),",
    "     mime_type     text NOT NULL,",
    "     data_url      text NOT NULL,",
    "     thumbnail_url text,",
    "     title         text,",
    "     description   text",
    "   );",
    "   ALTER TABLE media ENABLE ROW LEVEL SECURITY;",
    "   ```",
    "   Then choose the RLS policy based on visibility:",
    "   - Personal library (per-user private): use the owner policy from §0e.",
    "   - PUBLIC / COMMUNITY / SHARED gallery (\"anyone with the link can view + contribute\"): use a public policy — `CREATE POLICY media_public ON media USING (true) WITH CHECK (true);`. Do NOT apply the §0e owner policy here — it would hide every user's uploads from every other user, which is the OPPOSITE of what the user asked for.",
    "",
    "1. **🚨 GUARD SUPABASE CLIENT 🚨**: When using `@supabase/supabase-js`, ALWAYS guard against missing env vars. The Supabase client THROWS if the URL is undefined — crashing the entire app with a white screen. Write it like this:",
    "   ```ts",
    "   const url = import.meta.env.VITE_SUPABASE_URL ?? \"\";",
    "   const key = import.meta.env.VITE_SUPABASE_ANON_KEY ?? \"\";",
    "   export const supabase = url ? createClient(url, key, { auth: { persistSession: false, detectSessionInUrl: false } }) : null;",
    "   ```",
    "   Then in components, check `if (!supabase)` and show a \"Connecting to database...\" placeholder instead of crashing.",
    "   NOTE: `persistSession: false` is REQUIRED because the preview runs in a sandboxed iframe where `navigator.locks` is blocked.",
  ].join("\n"),

  routing: [
    "2. **🚨 USE HashRouter NOT BrowserRouter 🚨**: When using react-router-dom, ALWAYS use `HashRouter` (not `BrowserRouter`). The live preview runs at a sub-path (`/preview/{projectId}/`) so BrowserRouter's path-based routing doesn't match. HashRouter uses `#/` which works at any base URL. Import: `import { HashRouter, Routes, Route } from \"react-router-dom\";`",
    "",
    "   **🚨 ONLY ONE ROUTER — IN App.tsx ONLY 🚨**: You MUST place the `<HashRouter>` wrapper ONLY inside `src/App.tsx`. NEVER add a Router in `src/main.tsx` — that file is fixed infrastructure (ErrorBoundary + StrictMode + `<App />`). If you put `<HashRouter>` in BOTH main.tsx and App.tsx you get \"You cannot render a <Router> inside another <Router>\" which crashes the preview to a white screen. Pattern:",
    "   ```tsx",
    "   // src/App.tsx — Router goes HERE",
    "   export default function App() {",
    "     return (",
    "       <HashRouter>",
    "         <Routes>",
    "           <Route path=\"/\" element={<Home />} />",
    "         </Routes>",
    "       </HashRouter>",
    "     );",
    "   }",
    "   ```",
    "   NEVER do this in main.tsx:",
    "   ```tsx",
    "   // ❌ WRONG — main.tsx must NOT have a Router",
    "   <HashRouter><App /></HashRouter>",
    "   ```",
  ].join("\n"),

  styling: [
    "6. **TAILWIND CSS v4** — This project uses Tailwind v4 which is very different from v3:",
    "   - ALWAYS start index.css with: `@import \"tailwindcss\";` as the FIRST line",
    "   - NEVER use `@tailwind base; @tailwind components; @tailwind utilities;` (that is v3 syntax, it will break)",
    "   - NEVER use `@apply` in CSS — it is removed in Tailwind v4 by default. Use utility classes directly in JSX instead.",
    "   - NEVER create a tailwind.config.ts or tailwind.config.js — it's not needed. Tailwind v4 auto-detects utility classes.",
    "   - For custom theme values (colors, fonts, spacing), use the `@theme` directive in CSS:",
    "     ```css",
    "     @import \"tailwindcss\";",
    "     @theme {",
    "       --color-brand: #3b82f6;",
    "       --font-heading: \"Inter\", sans-serif;",
    "     }",
    "     ```",
    "   - Then use them as classes: `className=\"text-brand font-heading\"`",
    "   - **🚨 NEVER STRIP THE SHADCN @THEME COLOR BRIDGES 🚨** — the scaffold's `index.css` defines `--background`, `--foreground`, `--muted`, `--card`, `--border`, `--primary`, etc. as raw HSL triplets under `:root`/`.dark`, AND aliases them inside `@theme` as `--color-background: hsl(var(--background))`, `--color-foreground: hsl(var(--foreground))`, etc.",
    "   - Tailwind v4 ONLY emits a utility (`.text-foreground`, `.bg-background`, `.text-card-foreground`, etc.) when its underlying `--color-*` token exists inside `@theme`. If you remove or shrink the `@theme` block, those utilities silently disappear and every element using them renders with no color rule → invisible text.",
    "   - When you EDIT `index.css`, you may ADD new tokens (e.g. `--color-accent: hsl(...)`) but you MUST PRESERVE every `--color-*` line that already exists. If you rewrite the file from scratch, copy the existing `@theme` block VERBATIM — do not collapse it to just brand/font/radius tokens.",
  ].join("\n"),

  fileShape: [
    "7. **DEFAULT EXPORT**: src/App.tsx must use `export default` since src/main.tsx imports it as a default import.",
    "",
    "10. **FILE EXTENSIONS**: Always use `.tsx` for files containing JSX/TSX markup. Use `.ts` for pure TypeScript files with no JSX. Never put JSX in a `.ts` file.",
    "",
    "11. **IMPORT TYPES**: Do not use `import type { X }` for values that are used at runtime (e.g., as a component, in a function call, or as a value). `import type` strips the import at compile time, causing runtime errors. Only use `import type` for values used exclusively in type annotations.",
    "",
    "13. **FILE TOOLS — USE ONLY `create_file` / `edit_file` WITH RELATIVE PATHS**: To create or modify ANY file you MUST use Doable's `create_file` and `edit_file` tools. NEVER use the built-in editor tools `str_replace_editor`, `str_replace`, `edit`, `multi_edit`, `view`, `write`, or `create` — they expect absolute `/app/...` paths and a read-before-edit protocol that DO NOT apply here and will only waste your turns with errors like \"File already exists\", \"File has not been read yet\", or \"Path must be absolute\". If you EVER see one of those errors, STOP using that tool and switch to `create_file`/`edit_file` with a project-relative path. `create_file` OVERWRITES the file if it already exists, so for a full-file change just call `create_file` directly — you do NOT need to read, view, or delete the file first. The fields are EXACTLY:",
    "   - `path` (string, RELATIVE to the project root, e.g. `\"index.css\"`, `\"src/App.tsx\"`)",
    "   - `content` (string, the full file content)",
    "   Do NOT use `file_text` — that field does not exist on these tools. Do NOT pass `command: \"create\"` — these tools don't take a command field. Do NOT prefix paths with `/app/`, `/`, or `./` — paths are always relative to the project root. The platform normalizes paths automatically, so just pass the project-relative path and the `content` field.",
    "   Example: `create_file({ path: \"src/App.tsx\", content: \"export default function App() { return <div>Hi</div>; }\" })`",
  ].join("\n"),

  pwa: [
    "12. **PWA (Progressive Web App)**: When the user asks to make the app installable, work offline, or become a PWA:",
    "   - Install `vite-plugin-pwa` (devDependency) and `idb-keyval` (dependency)",
    "   - **CRITICAL**: Add `import { VitePWA } from \"vite-plugin-pwa\"` and `VitePWA({...})` to the plugins array in vite.config.ts — WITHOUT this, NO service worker, manifest, or registerSW.js will be generated",
    "   - Configure manifest INSIDE VitePWA() options (do NOT create a separate manifest.json)",
    "   - Use `scope: \"./\"` and `start_url: \"./\"` (relative paths — required for sub-path deployment)",
    "   - NEVER create sw.js manually — vite-plugin-pwa auto-generates it via Workbox",
    "   - NEVER call navigator.serviceWorker.register() — the plugin handles it",
    "   - Add to index.html: meta theme-color, apple-mobile-web-app-capable, apple-touch-icon, viewport-fit=cover",
    "   - Provide icons: 192×192 + 512×512 PNG (include one with purpose: \"maskable\")",
    "   - Add BeforeInstallPromptEvent type declaration in vite-env.d.ts",
    "   - **IMPORTANT**: Wrap ALL idb-keyval/IndexedDB calls in try/catch — the preview iframe sandbox blocks IndexedDB; fall back to in-memory or localStorage on SecurityError",
    "   - Caching: CacheFirst for static assets/fonts, NetworkFirst for API calls",
    "   - Add env(safe-area-inset-*) padding on body for iPhone notch",
  ].join("\n"),
};

